### PR TITLE
Expose more gateload props

### LINKED ISSUE #893: Expose new gateload params in Jenkins Perf job
Todo:
- [x] Update Jenkins job
- [x] Run a few sanity tests - http://uberjenkins.sc.couchbase.com/view/Performance/job/sync-gateway-perf-test/403/console

Need to parametrize these in Gateload config:
- SleepTimeMs
- ChannelActiveUsers
- ChannelConcurrentUsers

### PR DESCRIPTION
**Pull request by sethrosetter**
TODO:
- [x] Expose props in jenkins
- [x] Ran a sanity test and ensure all props are being set correctly after refactor

#### Fixes #893.

- [x] Ran `flake8`

#### Changes proposed in this pull request:

- Exposes SleepTimeMs, ChannelActiveUsers, ChannelConcurrentUsers to perf script
- Wrap gateload params in a named tuple to simplify the number of args we are passing around

### CODE REVIEW

**Comment by raghusarangapani** [comment]
Looks ok to me. I'll let Traun take another look and merge.

**Comment by tleyden** [comment]
Just ran into a problem with this on [this perf run](http://uberjenkins.sc.couchbase.com/view/Performance/job/sync-gateway-perf-test-copy-ro/43/console).

I can see the config being generated is invalid:

```
{
    "Hostname": "ec2-54-161-50-89.compute-1.amazonaws.com",
    "Port": 4984,
    "AdminPort": 4985,
    "Database": "db",
    "DocSize": 1024,
    "SendAttachment": false,
    "RampUpIntervalMs": 1800000,
    "RunTimeMs": 3600000,
    "SleepTimeMs": None,
    "NumPullers": 10000,
    "NumPushers": 10000,
    "ChannelActiveUsers": None,
    "ChannelConcurrentUsers": None,
    "MinUserOffTimeMs": 0,
    "MaxUserOffTimeMs": 0,
    "Verbose": false,
    "LogRequests": false,
    "UserOffset": 0,
    "AuthType": "basic",
    "Password": "password",
    "StatsdEnabled":true,
    "FeedType": "continuous",
    "StatsdEndpoint":"localhost:8125"
}
```
Invalid part: ` "SleepTimeMs": None,`

Looks like it might be due to the fact that this jenkins job doesn't have those new variables defined.

**Comment by sethrosetter** [comment]
@tleyden Which job is it?

**Comment by tleyden** [comment]
[sync-gateway-perf-test-copy-ro](http://uberjenkins.sc.couchbase.com/view/Performance/job/sync-gateway-perf-test-copy-ro)  -- I fixed it by updating the call to the run_gateload.py script and adding new variables.

Maintaining two jenkins jobs is painful, wish there was a better way

**Pull request merged**
