### PR TITLE
Remove subprocess for installing sync_gateway for shared listener tests

### PR DESCRIPTION
**Pull request by sethrosetter**
- move runtime version check to keyword level
- Install Sync Gateway now uses ansible API approach

---
This change is [Reviewable](https://reviewable.io/reviews/couchbaselabs/mobile-testkit/499)

### CODE REVIEW

**Comment by tleyden** [comment]
Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[keywords/SyncGateway.py, line 14 \[r1\]](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/499#-KJIhT4O-i7hau9DUxEX:-KJIhT4O-i7hau9DUxEY:-709623331) ([raw file](https://github.com/couchbaselabs/mobile-testkit/blob/0907828e61e11368869dd6a080252009e56a4135/keywords/SyncGateway.py#L14)):*
> ```Python
> 
> from constants import *
> from utils import *
> ```

It's my understanding that `import *` is considered a bad practice, and I will say that sometimes it does make it harder to track down where things are coming from.

---

*[keywords/SyncGateway.py, line 25 \[r1\]](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/499#-KJIhjlPCaFkCZRpm8cl:-KJIhjlPCaFkCZRpm8cm:-285094109) ([raw file](https://github.com/couchbaselabs/mobile-testkit/blob/0907828e61e11368869dd6a080252009e56a4135/keywords/SyncGateway.py#L25)):*
> ```Python
> 
>     running_version = resp_obj["version"]
>     running_version_parts = re.split("[ /(;)]", running_version)
> ```

I think it might be easier to understand with a comment that shows an example version string.. either in the method docs or above the code.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/499)*

**Comment by sethrosetter** [comment]
Review status: 10 of 11 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[keywords/SyncGateway.py, line 14 \[r1\]](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/499#-KJIhT4O-i7hau9DUxEX:-KJIpQxdBj8UcPoghLjJ:-497468049) ([raw file](https://github.com/couchbaselabs/mobile-testkit/blob/0907828e61e11368869dd6a080252009e56a4135/keywords/SyncGateway.py#L14)):*
<details><summary><i>Previously, tleyden (Traun Leyden) wrote…</i></summary>
> It's my understanding that `import *` is considered a bad practice, and I will say that sometimes it does make it harder to track down where things are coming from.
</details>
Fixed

---

*[keywords/SyncGateway.py, line 25 \[r1\]](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/499#-KJIhjlPCaFkCZRpm8cl:-KJIsMPwMB7PFqKc7MI4:-497468049) ([raw file](https://github.com/couchbaselabs/mobile-testkit/blob/0907828e61e11368869dd6a080252009e56a4135/keywords/SyncGateway.py#L25)):*
<details><summary><i>Previously, tleyden (Traun Leyden) wrote…</i></summary>
> I think it might be easier to understand with a comment that shows an example version string.. either in the method docs or above the code.
</details>
Fixed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/499)*

**Comment by tleyden** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/499)*

**Comment by tleyden** [comment]
Reviewed 4 of 7 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/499)*

**Pull request merged**
