### PR TITLE
Fixes #620 Write functional test for https://github.com/couchbase/syn…

### LINKED ISSUE #620: Write functional test for https://github.com/couchbase/sync_gateway/issues/2013
After the internal test provider supports this, need to test against internal test provider configured to return unsigned ID token (to replicate Azure behaviour).

### PR DESCRIPTION
**Pull request by tleyden**
…c_gateway/issues/2013

https://github.com/couchbaselabs/mobile-testkit/issues/620

https://github.com/couchbase/sync_gateway/issues/2013

---
This change is [Reviewable](https://reviewable.io/reviews/couchbaselabs/mobile-testkit/649)

### CODE REVIEW

**Comment by sethrosetter** [comment]
Can you kick off a sanity run in jenkins?

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/649#-:-KPyNIbQpRU001u3dG-8:b-ft2wjz)*

**Comment by tleyden** [comment]
Yeah, in progress here: http://uberjenkins.sc.couchbase.com/view/QE%20Dev/job/syncgateway-functional-tests-dev/135/console

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/649#-:-KPyXNTDpHuH48kRX1yg:burk7ch)*

**Comment by tleyden** [comment]
Seeing a func test failure in the openid connect tests:

```
KEYWORD test_openid_connect . Test Openidconnect Negative Token Expiry sg_url=${sg_url}, sg_db=${sg_db}
Start / End / Elapsed:	20160824 15:00:25.192 / 20160824 15:00:25.724 / 00:00:00.532
15:00:25.193	DEBUG	Test timeout 10 minutes active. 585.072 seconds left.	
15:00:25.193	INFO	Invoking _oidc_challenge against: http://s61803cnt72.sc.couchbase.com:4984/db/_oidc_challenge?provider=test	
15:00:25.195	INFO	Starting new HTTP connection (1): s61803cnt72.sc.couchbase.com	
15:00:25.501	DEBUG	"GET /db/_oidc_challenge?provider=test HTTP/1.1" 401 50	
15:00:25.503	INFO	Starting new HTTP connection (1): s61803cnt72.sc.couchbase.com	
15:00:25.506	DEBUG	"GET /db/_oidc_testing/authorize?client_id=sync_gateway&redirect_uri=http%3A%2F%2Fs61803cnt72.sc.couchbase.com%3A4984%2Fdb%2F_oidc_callback&response_type=code&scope=openid+email&state= HTTP/1.1" 200 1632	
15:00:25.508	INFO	Starting new HTTP connection (1): s61803cnt72.sc.couchbase.com	
15:00:25.510	DEBUG	"POST /db/_oidc_testing/authenticate?client_id=sync_gateway&redirect_uri=http%3A%2F%2Fs61803cnt72.sc.couchbase.com%3A4984%2Fdb%2F_oidc_callback&response_type=code&scope=openid+email&state= HTTP/1.1" 302 0	
15:00:25.723	DEBUG	"GET /db/_oidc_callback?code=dGVzdHVzZXI%3D&state=af0ifjsldkj HTTP/1.1" 400 63	
15:00:25.724	FAIL	AssertionError	
15:00:25.724	DEBUG	Traceback (most recent call last):
  File "/var/jenkins/workspace/syncgateway-functional-tests-dev/mobile-testkit/testsuites/syncgateway/functional/test_openid_connect.py", line 314, in test_openidconnect_negative_token_expiry
    assert response.status_code == 500
```

**Comment by tleyden** [comment]
@sethrosetter there was only one openid connect test that failed in http://uberjenkins.sc.couchbase.com/view/QE%20Dev/job/syncgateway-functional-tests-dev/135/console, and it's not related to the mobile-testkit changes as part of this PR -- it's [failing](http://uberjenkins.sc.couchbase.com/view/QE%20Dev/job/syncgateway-functional-tests-dev/137/console) on the master branch of mobile-testkit as well.

**Comment by tleyden** [comment]
Merged this so we don't forget about it

**Pull request merged**
