### PR TITLE
Feature/implement ttl functional tests

### LINKED ISSUE #506: Implement sync_gateway ttl tests
~~Waiting on https://github.com/couchbase/sync_gateway/issues/1805~~

### Scenarios
- [x] Numeric Expiry as TTL
- [x] String Expiry as TTL
- [x] Numeric Expiry as Unix Date
- [x] String Expiry as Unix Date
- [x] String Expiry as ISO-8601 Date
- [x] Removing expiry
- [x] Rolling TTL
- [x] Rolling TTL Expires
- [x] Setting expiry in bulk docs
- [ ] Validating retrieval of expiry value (Optional)

### PR DESCRIPTION
**Pull request by sethrosetter**
Fixes #506 

- Vagrant file now uses private network again due to genymotion workaround
- 'Create Doc' keyword now takes optional expiry
- Add 'Create Docs' keyword
- Add optional expiry and delay to 'Update Docs'
- Add 'Add Bulk Docs' keyword
- Add 'Get Bulk Docs' keyword
- Add 'Verify Doc Ids Found In Response' keyword
- Add 'Verify Doc Ids Not Found In Response' keyword
- Add 'Get Unix Timestamp' keyword
- Add 'Get ISO Datetime' keyword'
- Implement functional tests for ttl sync_gateway feature

---
This change is [Reviewable](https://reviewable.io/reviews/couchbaselabs/mobile-testkit/549)

### CODE REVIEW

**Comment by tleyden** [comment]
Review status: 0 of 6 files reviewed at latest revision, 8 unresolved discussions.

---

*[Vagrantfile, line 11 \[r1\]](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/549#-KL3kEd231Rj8_LQGGrb:-KL3kEd231Rj8_LQGGrc:-171638904) ([raw file](https://github.com/couchbaselabs/mobile-testkit/blob/be4f227b26c5a9c982522de3eab8be6ddda5e107/Vagrantfile#L11)):*
> ```Ruby
> 
>   host_ip = {
>     "host1" => "192.168.33.10",
> ```

I have an existing cluster, is this change going to break it?  How should I handle it?

---

*[Vagrantfile, line 30 \[r1\]](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/549#-KL3kNCbSphAb0dqQ1i0:-KL3kNCbSphAb0dqQ1i1:1105905195) ([raw file](https://github.com/couchbaselabs/mobile-testkit/blob/be4f227b26c5a9c982522de3eab8be6ddda5e107/Vagrantfile#L30)):*
> ```Ruby
> 
>             # Resync the vm and host time every 10 seconds
>             vb.customize ["guestproperty", "set", :id, "/VirtualBox/GuestAdd/VBoxService/--timesync-set-threshold", 10000]
> ```

Did you say this wasn't known to be working?

---

*[keywords/MobileRestClient.py, line 745 \[r1\]](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/549#-KL3kWh_sHv-G1LS6LAe:-KL3kWh_sHv-G1LS6LAf:-2031571557) ([raw file](https://github.com/couchbaselabs/mobile-testkit/blob/be4f227b26c5a9c982522de3eab8be6ddda5e107/keywords/MobileRestClient.py#L745)):*
> ```Python
> 
>             if delay is not None:
>                 time.sleep(delay)
> ```

Can you add a logging statement `sleeping x seconds`?

---

*[keywords/MobileRestClient.py, line 823 \[r1\]](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/549#-KL3kfItm2_zTP97hTvu:-KL3kfItm2_zTP97hTvv:467962072) ([raw file](https://github.com/couchbaselabs/mobile-testkit/blob/be4f227b26c5a9c982522de3eab8be6ddda5e107/keywords/MobileRestClient.py#L823)):*
> ```Python
>         """
> 
>         logging.debug(docs)
> ```

will this produce a lot of noise in logs?  I feel like callers can log this when they need to

---

*[keywords/MobileRestClient.py, line 842 \[r1\]](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/549#-KL3knq2uy6iHj2UJf40:-KL3knq2uy6iHj2UJf41:-1807543546) ([raw file](https://github.com/couchbaselabs/mobile-testkit/blob/be4f227b26c5a9c982522de3eab8be6ddda5e107/keywords/MobileRestClient.py#L842)):*
> ```Python
> 
>         resp_obj = parse_multipart_response(resp.text)
>         logging.debug(resp_obj)
> ```

should this be using log_info?  (the one that goes to robot console as well)

---

*[keywords/Time.py, line 16 \[r1\]](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/549#-KL3l4R9mqxZ2PeCRN0f:-KL3l4R9mqxZ2PeCRN0g:1433839548) ([raw file](https://github.com/couchbaselabs/mobile-testkit/blob/be4f227b26c5a9c982522de3eab8be6ddda5e107/keywords/Time.py#L16)):*
> ```Python
> 
>         unix_time_now= int(time.time())
>         log_info("Unix timestamp: {}".format(unix_time_now))
> ```

This feels like it will generate a lot of log noise

---

*[keywords/Time.py, line 18 \[r1\]](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/549#-KL3l8LJmdFxtIGiyQ-H:-KL3l8LJmdFxtIGiyQ-I:1433839548) ([raw file](https://github.com/couchbaselabs/mobile-testkit/blob/be4f227b26c5a9c982522de3eab8be6ddda5e107/keywords/Time.py#L18)):*
> ```Python
>         log_info("Unix timestamp: {}".format(unix_time_now))
>         timestamp_with_delta = unix_time_now + delta
>         log_info("Unix timestamp with delta: {}".format(timestamp_with_delta))
> ```

This feels like it will generate a lot of log noise

---

*[keywords/Time.py, line 38 \[r1\]](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/549#-KL3lCl4I60D1UdpRpEk:-KL3lCl4I60D1UdpRpEl:1433839548) ([raw file](https://github.com/couchbaselabs/mobile-testkit/blob/be4f227b26c5a9c982522de3eab8be6ddda5e107/keywords/Time.py#L38)):*
> ```Python
> 
>         log_info("Now: {}".format(timestamp_now))
>         log_info("With delta: {}".format(timestamp_with_delta))
> ```

This feels like it will generate a lot of log noise

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/549)*

**Comment by sethrosetter** [comment]
Review status: 0 of 6 files reviewed at latest revision, 8 unresolved discussions.

---

*[Vagrantfile, line 11 \[r1\]](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/549#-KL3kEd231Rj8_LQGGrb:-KLEGruHTCt4ecT4EDfx:1058119073) ([raw file](https://github.com/couchbaselabs/mobile-testkit/blob/be4f227b26c5a9c982522de3eab8be6ddda5e107/Vagrantfile#L11)):*
<details><summary><i>Previously, tleyden (Traun Leyden) wrote…</i></summary>
> I have an existing cluster, is this change going to break it?  How should I handle it?
</details>
If you are targeting a private network with these same endpoints, you should be fine. If your endpoints are different, just save your current Vagrantfile to a temp file, pull and then replace the Vagrantfile with the one you saved. 

---

*[Vagrantfile, line 30 \[r1\]](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/549#-KL3kNCbSphAb0dqQ1i0:-KLEHD-t12sjjB9YqyxG:649271467) ([raw file](https://github.com/couchbaselabs/mobile-testkit/blob/be4f227b26c5a9c982522de3eab8be6ddda5e107/Vagrantfile#L30)):*
<details><summary><i>Previously, tleyden (Traun Leyden) wrote…</i></summary>
> Did you say this wasn't known to be working?
</details>
Oh good call, I will remove it.

---

*[keywords/MobileRestClient.py, line 745 \[r1\]](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/549#-KL3kWh_sHv-G1LS6LAe:-KLEHfo0RQVHvLdFLwNJ:-499146009) ([raw file](https://github.com/couchbaselabs/mobile-testkit/blob/be4f227b26c5a9c982522de3eab8be6ddda5e107/keywords/MobileRestClient.py#L745)):*
<details><summary><i>Previously, tleyden (Traun Leyden) wrote…</i></summary>
> Can you add a logging statement `sleeping x seconds`?
</details>
Done.

---

*[keywords/MobileRestClient.py, line 823 \[r1\]](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/549#-KL3kfItm2_zTP97hTvu:-KLEHmI7u93k6A75wcOV:-499146009) ([raw file](https://github.com/couchbaselabs/mobile-testkit/blob/be4f227b26c5a9c982522de3eab8be6ddda5e107/keywords/MobileRestClient.py#L823)):*
<details><summary><i>Previously, tleyden (Traun Leyden) wrote…</i></summary>
> will this produce a lot of noise in logs?  I feel like callers can log this when they need to
</details>
Done.

---

*[keywords/MobileRestClient.py, line 842 \[r1\]](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/549#-KL3knq2uy6iHj2UJf40:-KLEHpO3kZZG1NO_dRhF:668980661) ([raw file](https://github.com/couchbaselabs/mobile-testkit/blob/be4f227b26c5a9c982522de3eab8be6ddda5e107/keywords/MobileRestClient.py#L842)):*
<details><summary><i>Previously, tleyden (Traun Leyden) wrote…</i></summary>
> should this be using log_info?  (the one that goes to robot console as well)
</details>
I think this is fine. I am already using `log_r` for the request / reponse a couple lines above which will include lightweight console / info logging. I think this should remain debug to avoid too much noise. 

---

*[keywords/Time.py, line 16 \[r1\]](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/549#-KL3l4R9mqxZ2PeCRN0f:-KLEIJC_rDR7Z37UJ5oD:-266112863) ([raw file](https://github.com/couchbaselabs/mobile-testkit/blob/be4f227b26c5a9c982522de3eab8be6ddda5e107/keywords/Time.py#L16)):*
<details><summary><i>Previously, tleyden (Traun Leyden) wrote…</i></summary>
> This feels like it will generate a lot of log noise
</details>
I think it is ok since it is used only once and is important in debugging the test (i.e. clock drift issues).

---

*[keywords/Time.py, line 18 \[r1\]](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/549#-KL3l8LJmdFxtIGiyQ-H:-KLEIP3x_sLM8pWt-RZS:-266112863) ([raw file](https://github.com/couchbaselabs/mobile-testkit/blob/be4f227b26c5a9c982522de3eab8be6ddda5e107/keywords/Time.py#L18)):*
<details><summary><i>Previously, tleyden (Traun Leyden) wrote…</i></summary>
> This feels like it will generate a lot of log noise
</details>
I think it is ok since it is used only once and is important in debugging the test (i.e. clock drift issues).

---

*[keywords/Time.py, line 38 \[r1\]](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/549#-KL3lCl4I60D1UdpRpEk:-KLEIRWanLhVFR8omI7g:-266112863) ([raw file](https://github.com/couchbaselabs/mobile-testkit/blob/be4f227b26c5a9c982522de3eab8be6ddda5e107/keywords/Time.py#L38)):*
<details><summary><i>Previously, tleyden (Traun Leyden) wrote…</i></summary>
> This feels like it will generate a lot of log noise
</details>
I think it is ok since it is used only once and is important in debugging the test (i.e. clock drift issues).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/549)*

**Comment by tleyden** [comment]
Reviewed 1 of 2 files at r2.
Review status: 1 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/549)*

**Comment by tleyden** [comment]
Reviewed 4 of 6 files at r1, 1 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/549)*

**Comment by tleyden** [comment]
Merged, but still a bit confused about:

> If you are targeting a private network with these same endpoints, you should be fine. If your endpoints are different, just save your current Vagrantfile to a temp file, pull and then replace the Vagrantfile with the one you saved.


When you say "Same endpoints", same as what?  Also, if I change my Vagrantfile do I need to destroy and recreate my VM cluster?

**Pull request merged**
