### PR TITLE
Fixes #1774 Functional tests for OIDC authentication

### PR DESCRIPTION
**Pull request by tleyden**
This change is [Reviewable](https://reviewable.io/reviews/couchbaselabs/mobile-testkit/541)

### CODE REVIEW

**Comment by tleyden** [comment]
This includes fix for #1774 

Jenkins functional test in progress:

http://uberjenkins.sc.couchbase.com:8080/view/QE%20Dev/job/syncgateway-functional-tests-dev/121/

**Comment by tleyden** [comment]
@ajres included you as part of the PR review, we should plan to do a screenshare session with the three of us.

**Comment by tleyden** [comment]
@seth I pushed up the changes we discussed and rebased off current master.

Functional test re-run in progress: 

http://uberjenkins.sc.couchbase.com:8080/view/QE%20Dev/job/syncgateway-functional-tests-dev/132/console

**Comment by sethrosetter** [comment]
Reviewed 4 of 7 files at r1, 1 of 1 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[testsuites/syncgateway/functional/test_openid_connect.py, line 88 \[r3\]](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/541#-KKusO_-SwiwkwEpck4u:-KKusO_0-9xMbRB0BuHr:3364680) ([raw file](https://github.com/couchbaselabs/mobile-testkit/blob/396ef834e8f7198144898b46327da71fd92195f9/testsuites/syncgateway/functional/test_openid_connect.py#L88)):*
> ```Python
>     www_auth_header = response.headers['Www-Authenticate']
>     max_split = 1
>     oidc_login_url = www_auth_header.split("=", max_split)[1]              # '"http://localhost:4984/db/_oid ..."'
> ```

This comment is confusing

---

*[testsuites/syncgateway/functional/test_openid_connect.py, line 147 \[r3\]](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/541#-KKuuvBVZcEAEp01kPgM:-KKuuvBVZcEAEp01kPgN:59000984) ([raw file](https://github.com/couchbaselabs/mobile-testkit/blob/396ef834e8f7198144898b46327da71fd92195f9/testsuites/syncgateway/functional/test_openid_connect.py#L147)):*
> ```Python
>     # make a request using the ID token against the db and expect a 200 response
>     headers = {"Authorization": "Bearer {}".format(id_token)}
>     db_url = "{}/{}".format(sg_url, sg_db)
> ```

Can we assume that if we have authorization to the db endpoint, that all other endpoints will function as expected?

---

*[testsuites/syncgateway/functional/test_openid_connect.py, line 177 \[r3\]](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/541#-KKuuaj9lGOHL_xIXWlr:-KKuuaj9lGOHL_xIXWls:-944388167) ([raw file](https://github.com/couchbaselabs/mobile-testkit/blob/396ef834e8f7198144898b46327da71fd92195f9/testsuites/syncgateway/functional/test_openid_connect.py#L177)):*
> ```Python
>         # make sure we get a unique id token each time
>         assert id_token_refresh not in id_tokens
>         id_tokens.append(id_token_refresh)
> ```

Would it be a good assertion to test that the new id tokens can also communicate with the live sync gateway (i.e. GET /db)?

---

*[testsuites/syncgateway/functional/test_openid_connect.py, line 262 \[r3\]](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/541#-KKuvenp_c9E3Bmkwl4a:-KKuvenq-ODCr9hlrATQ:910896144) ([raw file](https://github.com/couchbaselabs/mobile-testkit/blob/396ef834e8f7198144898b46327da71fd92195f9/testsuites/syncgateway/functional/test_openid_connect.py#L262)):*
> ```Python
>     id_token = response_json["id_token"]
> 
>     time.sleep(token_expiry_seconds * 2)
> ```

Why * 2, should a delta of + 1 be sufficient?

---

*[testsuites/syncgateway/functional/test_openid_connect.py, line 319 \[r3\]](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/541#-KKuw8AvnpcSnfVJEYyZ:-KKuw8AvnpcSnfVJEYy_:1111355695) ([raw file](https://github.com/couchbaselabs/mobile-testkit/blob/396ef834e8f7198144898b46327da71fd92195f9/testsuites/syncgateway/functional/test_openid_connect.py#L319)):*
> ```Python
> 
>     # add a garbage last component
>     all_components_except_last.append("garbage")
> ```

Should this be more realistic the last piece of the token, (i.e. expected length) or do you think this is fine?

---

*[testsuites/syncgateway/functional/test_openid_connect.py, line 408 \[r3\]](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/541#-KKuxQdTWv8a7dRSvjBq:-KKuxQdU03Qfc1_r3DAM:-738212420) ([raw file](https://github.com/couchbaselabs/mobile-testkit/blob/396ef834e8f7198144898b46327da71fd92195f9/testsuites/syncgateway/functional/test_openid_connect.py#L408)):*
> ```Python
>     log_info("decoded_id_token: {}".format(decoded_id_token))
> 
>     assert "nickname"  in decoded_id_token.keys()
> ```

Is more than "nickname" expected in a large scope or should we assert others as well?

---

*[testsuites/syncgateway/functional/1sg_1cbs/1sg_1cbs-openid-connect.robot, line 57 \[r3\]](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/541#-KKuxxX7-I12MwpvzAGg:-KKuxxX7-I12MwpvzAGh:562906970) ([raw file](https://github.com/couchbaselabs/mobile-testkit/blob/396ef834e8f7198144898b46327da71fd92195f9/testsuites/syncgateway/functional/1sg_1cbs/1sg_1cbs-openid-connect.robot#L57)):*
> ```RobotFramework
>     ...  and make sure the token is rejected
>     [Tags]   sanity
>     Test OpenIDConnect Expired Token  sg_url=${sg_url}  sg_db=${sg_db}
> ```

What is the behavior for a ttl on the token for the past?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/541)*

**Comment by tleyden** [comment]
Review status: 4 of 7 files reviewed at latest revision, 7 unresolved discussions.

---

*[testsuites/syncgateway/functional/test_openid_connect.py, line 88 \[r3\]](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/541#-KKusO_-SwiwkwEpck4u:-KL3jfqo2CHOlEtWuMRo:-499146009) ([raw file](https://github.com/couchbaselabs/mobile-testkit/blob/396ef834e8f7198144898b46327da71fd92195f9/testsuites/syncgateway/functional/test_openid_connect.py#L88)):*
<details><summary><i>Previously, sethrosetter (Seth Rosetter) wrote…</i></summary>
> This comment is confusing
</details>
Done.

---

*[testsuites/syncgateway/functional/test_openid_connect.py, line 147 \[r3\]](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/541#-KKuuvBVZcEAEp01kPgM:-KL3jlx_S6W-zs0gUr-r:-1283794533) ([raw file](https://github.com/couchbaselabs/mobile-testkit/blob/396ef834e8f7198144898b46327da71fd92195f9/testsuites/syncgateway/functional/test_openid_connect.py#L147)):*
<details><summary><i>Previously, sethrosetter (Seth Rosetter) wrote…</i></summary>
> Can we assume that if we have authorization to the db endpoint, that all other endpoints will function as expected?
</details>
Not sure I understand.  Are you saying that the test might be weak in the sense that it only validates one endpoint?

---

*[testsuites/syncgateway/functional/test_openid_connect.py, line 177 \[r3\]](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/541#-KKuuaj9lGOHL_xIXWlr:-KL3fboSUu17vUH_9mX-:-499146009) ([raw file](https://github.com/couchbaselabs/mobile-testkit/blob/396ef834e8f7198144898b46327da71fd92195f9/testsuites/syncgateway/functional/test_openid_connect.py#L177)):*
<details><summary><i>Previously, sethrosetter (Seth Rosetter) wrote…</i></summary>
> Would it be a good assertion to test that the new id tokens can also communicate with the live sync gateway (i.e. GET /db)?
</details>
Done.

---

*[testsuites/syncgateway/functional/test_openid_connect.py, line 262 \[r3\]](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/541#-KKuvenp_c9E3Bmkwl4a:-KL3g7hHpWi1PXdBE1_D:-499146009) ([raw file](https://github.com/couchbaselabs/mobile-testkit/blob/396ef834e8f7198144898b46327da71fd92195f9/testsuites/syncgateway/functional/test_openid_connect.py#L262)):*
<details><summary><i>Previously, sethrosetter (Seth Rosetter) wrote…</i></summary>
> Why * 2, should a delta of + 1 be sufficient?
</details>
Done.

---

*[testsuites/syncgateway/functional/test_openid_connect.py, line 319 \[r3\]](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/541#-KKuw8AvnpcSnfVJEYyZ:-KL3gBYrdN48WIcykVKn:-2048128754) ([raw file](https://github.com/couchbaselabs/mobile-testkit/blob/396ef834e8f7198144898b46327da71fd92195f9/testsuites/syncgateway/functional/test_openid_connect.py#L319)):*
<details><summary><i>Previously, sethrosetter (Seth Rosetter) wrote…</i></summary>
> Should this be more realistic the last piece of the token, (i.e. expected length) or do you think this is fine?
</details>
I think it's fine since I can't envision a scenario where it would be let through due to being garbage of the same length

---

*[testsuites/syncgateway/functional/test_openid_connect.py, line 408 \[r3\]](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/541#-KKuxQdTWv8a7dRSvjBq:-KL3gNYCgToMo7sNCPgA:-1603273766) ([raw file](https://github.com/couchbaselabs/mobile-testkit/blob/396ef834e8f7198144898b46327da71fd92195f9/testsuites/syncgateway/functional/test_openid_connect.py#L408)):*
<details><summary><i>Previously, sethrosetter (Seth Rosetter) wrote…</i></summary>
> Is more than "nickname" expected in a large scope or should we assert others as well?
</details>
Nickname is the only one I am aware of.  I think it's sufficient.

---

*[testsuites/syncgateway/functional/1sg_1cbs/1sg_1cbs-openid-connect.robot, line 57 \[r3\]](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/541#-KKuxxX7-I12MwpvzAGg:-KL3ixK-1XLIfJPlOEQ7:-55622286) ([raw file](https://github.com/couchbaselabs/mobile-testkit/blob/396ef834e8f7198144898b46327da71fd92195f9/testsuites/syncgateway/functional/1sg_1cbs/1sg_1cbs-openid-connect.robot#L57)):*
<details><summary><i>Previously, sethrosetter (Seth Rosetter) wrote…</i></summary>
> What is the behavior for a ttl on the token for the past?
</details>
Good catch!  I added a new test for that which is currently passing

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/541)*

**Comment by sethrosetter** [comment]
Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[testsuites/syncgateway/functional/test_openid_connect.py, line 147 \[r3\]](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/541#-KKuuvBVZcEAEp01kPgM:-KLEF7xXnpAAZ3y8_qRL:-1929006374) ([raw file](https://github.com/couchbaselabs/mobile-testkit/blob/396ef834e8f7198144898b46327da71fd92195f9/testsuites/syncgateway/functional/test_openid_connect.py#L147)):*
<details><summary><i>Previously, tleyden (Traun Leyden) wrote…</i></summary>
> Not sure I understand.  Are you saying that the test might be weak in the sense that it only validates one endpoint?
</details>
That is correct. Do we need to validate against other sync_gateway endpoints or can we assume that if we have access to the database endpoint that the access for the other endpoints we expect to be able to query will will work as expected.?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/541)*

**Pull request merged**
