### PR TITLE
Clean up README.md

### PR DESCRIPTION
**Pull request by sethrosetter**

### CODE REVIEW

**Comment by tleyden** [comment]
I was looking at a preview here ..

https://github.com/couchbaselabs/mobile-testkit/tree/feature/readme-cleanup#known-issues-and-limitations

Why is "Spin Up Machines on AWS" under "Known Issues And Limitations"?

**Comment by sethrosetter** [comment]
@tleyden Fixed

**Comment by tleyden** [comment]
Shouldn't this https://github.com/couchbaselabs/mobile-testkit/tree/feature/readme-cleanup#spin-up-machines-on-aws be under https://github.com/couchbaselabs/mobile-testkit/tree/feature/readme-cleanup#sync_gateway-tests?

**Comment by tleyden** [comment]
Also can you put "Repo Structure" as one of the items in the TOC?

**Comment by sethrosetter** [comment]
@tleyden Done

**Comment by tleyden** [comment]
It still looks wrong because "Spin Up Machines on AWS" is under "Monitoring"

**Comment by sethrosetter** [comment]
@tleyden This should be better

**Pull request merged**
