### PR TITLE
Add test scenario: Stale revision should not be in the index

### PR DESCRIPTION
**Pull request by hideki**
This change is [Reviewable](https://reviewable.io/reviews/couchbaselabs/mobile-testkit/502)

### CODE REVIEW

**Comment by sethrosetter** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[unimplemented/test_view_indexing.robot, line 10 \[r1\]](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/502#-KJMQLgPssARY-abPgo3:-KJMQLgPssARY-abPgo4:1488726531) ([raw file](https://github.com/couchbaselabs/mobile-testkit/blob/2308c7227e2f4dc506d9c3601fea367e5c934c75/unimplemented/test_view_indexing.robot#L10)):*
> ```RobotFramework
>     ...  1. Running sync_gateway
>     ...  2. Create database and starts both push and pull replicators
>     ...  3. Create two or more views
> ```

Create these on the client or sync_gateway?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/502)*

**Comment by sethrosetter** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[unimplemented/test_view_indexing.robot, line 11 \[r1\]](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/502#-KJMQrgzwr1u3mXsnl6e:-KJMQrgzwr1u3mXsnl6f:-1309866197) ([raw file](https://github.com/couchbaselabs/mobile-testkit/blob/2308c7227e2f4dc506d9c3601fea367e5c934c75/unimplemented/test_view_indexing.robot#L11)):*
> ```RobotFramework
>     ...  2. Create database and starts both push and pull replicators
>     ...  3. Create two or more views
>     ...  4. Add doc, and verify doc is index with current revision
> ```

If this is to be added on the client, can this be done via Listener?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/502)*

**Comment by hideki** [comment]
@seth, I updated test scenario

**Comment by sethrosetter** [comment]
Looks great. Thanks!

**Pull request merged**
