### PR TITLE
Feature/issue 564 dns names

### LINKED ISSUE #564: Configure DNS names for each AWS instance
This is needed in order to fix https://github.com/couchbaselabs/mobile-testkit/issues/559  (however, still more work for  https://github.com/couchbaselabs/mobile-testkit/issues/559 will be needed even after this issue is fixed)

I'm going to change the troposphere script to generate new cloudformation json that will contain entries like:

```
        "syncgateway0dns": {
            "Properties": {
                "HostedZoneName": "couchbasemobile.com.",
                "Name": "syncgateway0.cloudformationstack.couchbasemobile.com",
                "ResourceRecords": [
                    {
                        "Fn::GetAtt": [
                            "syncgateway0",
                            "PublicIp"
                        ]
                    }
                ],
                "TTL": "900",
                "Type": "A"
            },
            "Type": "AWS::Route53::RecordSet"
        },
```

where `cloudformationstack` will be the actual Cloudformation stack name.

### PR DESCRIPTION
**Pull request by tleyden**
Fixes #564

---
This change is [Reviewable](https://reviewable.io/reviews/couchbaselabs/mobile-testkit/565)

### CODE REVIEW

**Comment by sethrosetter** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[libraries/provision/cloudformation_template.py, line 234 \[r1\]](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/565#-KLOHTOMIYVgAUh4uWxg:-KLOHTOMIYVgAUh4uWxh:1716298613) ([raw file](https://github.com/couchbaselabs/mobile-testkit/blob/9e3a9407037798938cea67dbd0a44613b53f8c30/libraries/provision/cloudformation_template.py#L234)):*
> ```Python
> 
> 
> def create_dns_entry(instance, name, config):
> ```

Is name the name we provide to the cloudformation script?

---

*[libraries/provision/cloudformation_template.py, line 240 \[r1\]](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/565#-KLOH0weyQBMEi7Z4jpl:-KLOH0wfME0FGBvEgq0h:-1865946347) ([raw file](https://github.com/couchbaselabs/mobile-testkit/blob/9e3a9407037798938cea67dbd0a44613b53f8c30/libraries/provision/cloudformation_template.py#L240)):*
> ```Python
>             GetAtt(instance, "PublicIp")
>         ],
>         TTL="900",
> ```

What metric is this in?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/565)*

**Comment by tleyden** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[libraries/provision/cloudformation_template.py, line 234 \[r1\]](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/565#-KLOHTOMIYVgAUh4uWxg:-KLOKOAPpgO1vRIfNMG1:1134764357) ([raw file](https://github.com/couchbaselabs/mobile-testkit/blob/9e3a9407037798938cea67dbd0a44613b53f8c30/libraries/provision/cloudformation_template.py#L234)):*
<details><summary><i>Previously, sethrosetter (Seth Rosetter) wrote…</i></summary>
> Is name the name we provide to the cloudformation script?
</details>
name in this case will be couchbaseserver0, syncgateway1, etc.  resource type + index.

---

*[libraries/provision/cloudformation_template.py, line 240 \[r1\]](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/565#-KLOH0weyQBMEi7Z4jpl:-KLOK_41mbWRIBSQKvyd:-176065062) ([raw file](https://github.com/couchbaselabs/mobile-testkit/blob/9e3a9407037798938cea67dbd0a44613b53f8c30/libraries/provision/cloudformation_template.py#L240)):*
<details><summary><i>Previously, sethrosetter (Seth Rosetter) wrote…</i></summary>
> What metric is this in?
</details>
seconds

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/565)*

**Comment by sethrosetter** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[libraries/provision/cloudformation_template.py, line 240 \[r1\]](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/565#-KLOH0weyQBMEi7Z4jpl:-KLOLPS8kNNucTGXehab:-171627493) ([raw file](https://github.com/couchbaselabs/mobile-testkit/blob/9e3a9407037798938cea67dbd0a44613b53f8c30/libraries/provision/cloudformation_template.py#L240)):*
<details><summary><i>Previously, tleyden (Traun Leyden) wrote…</i></summary>
> seconds
</details>
Also with the ttl will that terminate the dns entry? Do we need that or can we terminate the entry with the instance. 15 min is not that long and the tests will fail right?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/565)*

**Comment by sethrosetter** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[libraries/provision/cloudformation_template.py, line 240 \[r1\]](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/565#-KLOH0weyQBMEi7Z4jpl:-KLOM9cvwskr36wb0k39:-352625073) ([raw file](https://github.com/couchbaselabs/mobile-testkit/blob/9e3a9407037798938cea67dbd0a44613b53f8c30/libraries/provision/cloudformation_template.py#L240)):*
<details><summary><i>Previously, sethrosetter (Seth Rosetter) wrote…</i></summary>
> Also with the ttl will that terminate the dns entry? Do we need that or can we terminate the entry with the instance. 15 min is not that long and the tests will fail right?
</details>
From @tleyden, the DNS entry will stay active until the Cloudformation is deleted

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/565)*

**Pull request merged**
