### PR TITLE
Handle cc / di user doc differences

### PR DESCRIPTION
**Pull request by sethrosetter**
- [x] Ran `flake8`

#### Changes proposed in this pull request:

- Fix tests to handle _user/ doc behavior differences
- Disable bucket shadow tests in di mode

### CODE REVIEW

**Comment by sethrosetter** [comment]
Just so I'm clear `CHANNEL-TO-ROLE-REST` and `CHANNEL-TO-ROLE-SYNC` should not see any user docs in the backfill, correct?

**Comment by adamcfraser** [comment]
@seth That's correct - the channel-to-role grant doesn't trigger a user doc update, so even a REST-based update shouldn't result in a user doc update.  We also don't have the concept of pseudo-role docs in the feed (i.e. we don't send a _role/rolename entry).

**Comment by tleyden** [comment]
> Disable bucket shadow tests in di mode

@adamcfraser If we are doing this, shouldn't we detect this config combo altogether to prevent users running in this mode?

**Comment by adamcfraser** [comment]
@tleyden Would be a nice enhancement but not a must-have for 1.4.

**Pull request merged**
