### PR TITLE
Remove route53 dns setup

### PR DESCRIPTION
**Pull request by jamiltz**

### CODE REVIEW

**Comment by sethrosetter** [comment]
@jamiltz Why is this necessary?

**Comment by jamiltz** [comment]
That was to deploy a 1SG and 1CBS setup to my personal AWS account which had no pre configured route53. Made the change with @tleyden.

**Comment by jamiltz** [comment]
I think we gave up on deploying to my personal account in the end but that was the intention with this PR. Hopefully it doesn't brake anything :| I'll try it again and report the results in https://github.com/couchbaselabs/mobile-testkit/issues/685

**Comment by sethrosetter** [comment]
Sweet! Thanks. Talked about it with @tleyden and it shouldn't hurt anything.

**Pull request merged**
