### PR TITLE
Ngrep capture

### PR DESCRIPTION
**Pull request by tleyden**
This change is [Reviewable](https://reviewable.io/reviews/couchbaselabs/mobile-testkit/455)

### CODE REVIEW

**Comment by tleyden** [comment]
Successful jenkins run on this branch: http://uberjenkins.sc.couchbase.com:8080/view/QE%20Dev/job/syncgateway-functional-tests-dev/34/

**Comment by sethrosetter** [comment]
Review status: 0 of 6 files reviewed at latest revision, 6 unresolved discussions.

---

*[libraries/NetworkUtils.py, line 20 \[r2\]](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/455#-KHbGSW3UEeciCOSI8Lv:-KHbGSW3UEeciCOSI8Lw:-313219672) ([raw file](https://github.com/couchbaselabs/mobile-testkit/blob/806e1718f59337012087289f04a7454742d2f8fb/libraries/NetworkUtils.py#L20)):*
> ```Python
>             stop_on_fail=False
>         )
>         assert (status == 0)
> ```

Can you add a string comment next to the assertions (for all of these)?

---

*[libraries/NetworkUtils.py, line 30 \[r2\]](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/455#-KHbHFhCk3dhaBkDwLql:-KHbHFhCk3dhaBkDwLqm:953159397) ([raw file](https://github.com/couchbaselabs/mobile-testkit/blob/806e1718f59337012087289f04a7454742d2f8fb/libraries/NetworkUtils.py#L30)):*
> ```Python
>         assert (status == 0)
> 
>     def collect_packet_capture(self):
> ```

pass test name from robot

---

*[libraries/NetworkUtils.py, line 39 \[r2\]](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/455#-KHbGuvn_rjwnZjtDDea:-KHbGuvn_rjwnZjtDDeb:1070332752) ([raw file](https://github.com/couchbaselabs/mobile-testkit/blob/806e1718f59337012087289f04a7454742d2f8fb/libraries/NetworkUtils.py#L39)):*
> ```Python
> 
>         # zip logs and timestamp
>         if os.path.isdir("/tmp/sg_logs"):
> ```

use /tmp/sys-logs or something similar

---

*[libraries/NetworkUtils.py, line 43 \[r2\]](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/455#-KHbH32z3jSBHVXHHBNK:-KHbH32z3jSBHVXHHBNL:-2070198739) ([raw file](https://github.com/couchbaselabs/mobile-testkit/blob/806e1718f59337012087289f04a7454742d2f8fb/libraries/NetworkUtils.py#L43)):*
> ```Python
>             name = "/tmp/ngrep-{}-sglogs".format(date_time)
>             shutil.make_archive(name, "zip", "/tmp/sg_logs")
>             shutil.rmtree("/tmp/sg_logs")
> ```

update to remove /tmp/sys-logs

---

*[libraries/provision/ansible/playbooks/collect-ngrep.yml, line 8 \[r2\]](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/455#-KHbIhBxUvqAGabwSdOW:-KHbIhBxUvqAGabwSdOX:839134561) ([raw file](https://github.com/couchbaselabs/mobile-testkit/blob/806e1718f59337012087289f04a7454742d2f8fb/libraries/provision/ansible/playbooks/collect-ngrep.yml#L8)):*
> ```YAML
>   tasks:
>   - name: fetch ngrep packet capture
>     fetch: src=/tmp/ngrep.txt dest=/tmp/sg_logs/ngrep_{{ inventory_hostname }}
> ```

update to use /tmp/syslogs

---

*[testsuites/syncgateway/functional/2sg_1cbs.robot, line 105 \[r2\]](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/455#-KHbLt0yF29rOFxZsflm:-KHbLt0yF29rOFxZsfln:-1400253789) ([raw file](https://github.com/couchbaselabs/mobile-testkit/blob/806e1718f59337012087289f04a7454742d2f8fb/testsuites/syncgateway/functional/2sg_1cbs.robot#L105)):*
> ```RobotFramework
>     List Connections
>     Stop Packet Capture
>     Collect Packet Capture
> ```

Pass test name ${TEST_NAME} here

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/455)*

**Comment by tleyden** [comment]
@sethrosetter ok this is ready to be merged!

Successful Jenkins run: http://uberjenkins.sc.couchbase.com:8080/view/QE%20Dev/job/syncgateway-functional-tests-dev/44/

**Comment by sethrosetter** [comment]
Reviewed 3 of 6 files at r1, 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/455)*

**Comment by sethrosetter** [comment]
:lgtm:

<details><summary><i>Previously, tleyden (Traun Leyden) wrote…</i></summary>
> @sethrosetter ok this is ready to be merged!
> 
> 
> 
> Successful Jenkins run: http://uberjenkins.sc.couchbase.com:8080/view/QE%20Dev/job/syncgateway-functional-tests-dev/44/</details>


---

Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/455#-:-KHvforC2Gp6VdcKGVhs:1417088721)*

**Comment by sethrosetter** [comment]
:lgtm:

<details><summary><i>Previously, sethrosetter (Seth Rosetter) wrote…</i></summary>
> :lgtm:</details>


---

Reviewed 1 of 6 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/455#-:-KHvgIsD8f_ILcLBu_7T:1417088721)*

**Comment by sethrosetter** [comment]
Reviewed 1 of 4 files at r3.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/455)*

**Pull request merged**
