### PR TITLE
Feature/update telegraf stats

### PR DESCRIPTION
**Pull request by tleyden**
#### Fixes #.

- [ x ] Ran `flake8`

#### Changes proposed in this pull request:

- Updates telegraf binary to push more stats required in https://github.com/couchbaselabs/sync-gateway-accel/issues/78
- Updates stored grafana dashboard json to show the new stats

screen shot 2017-02-07 at 11 14 48 am

### CODE REVIEW

**Comment by sethrosetter** [comment]
@tleyden Is this rebased?

**Comment by tleyden** [comment]
No but I don't think it necessarily needs to be

**Comment by sethrosetter** [comment]
@tleyden, Which stats were added? Not a blocker, just for history since it doesn't really show in the diff

**Comment by tleyden** [comment]
Here are the current set of stats being extracted from sync gw expvars now:

https://github.com/couchbaselabs/telegraf/blob/9468716730a7fe53c0f5e23c33ab17f1107a53d4/plugins/inputs/syncgateway/syncgateway.go#L133-L155

**Comment by tleyden** [comment]
Previously was just these two:

```
stats["memstatsAlloc"] = memstats["Alloc"];
stats["memstatsSys"] = memstats["Sys"];
```

**Pull request merged**
