### PR TITLE
Feature/issue 1910 perf test rebased

### PR DESCRIPTION
**Pull request by tleyden**
This change is [Reviewable](https://reviewable.io/reviews/couchbaselabs/mobile-testkit/575)

### CODE REVIEW

**Comment by sethrosetter** [comment]
Reviewed 34 of 34 files at r1.
Review status: 21 of 23 files reviewed at latest revision, 4 unresolved discussions.

---

*[libraries/provision/generate_pools_json_from_aws.py, line 26 \[r1\]](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/575#-KLcUjoT_S8Aq39qKNlt:-KLcUjoT_S8Aq39qKNlu:-820174059) ([raw file](https://github.com/couchbaselabs/mobile-testkit/blob/c699d7752b5a4c92086a87fe49f824e42aeca1a9/libraries/provision/generate_pools_json_from_aws.py#L26)):*
Personally I am a fan of with syntax

```
>>> with open('workfile', 'w') as f:
...     f.write("blah")
>>> f.closed
True
```

---

*[libraries/provision/generate_pools_json_from_aws.py, line 69 \[r1\]](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/575#-KLcs-RA6x4N4fvCBv7H:-KLcs-RA6x4N4fvCBv7I:821461497) ([raw file](https://github.com/couchbaselabs/mobile-testkit/blob/c699d7752b5a4c92086a87fe49f824e42aeca1a9/libraries/provision/generate_pools_json_from_aws.py#L69)):*
> ```Python
>     (opts, args) = parser.parse_args(arg_parameters)
> 
>     if opts.stackname is None or opts.targetfile is None:
> ```

Can we just put this to 'resources/pool.json' by default or have generate_clusters_from_pool.py take a target pool file? I like the second one more so we could support multiple pool.json files (i.e. pool-aws.json and pool-vagrant.json)

---

*[libraries/provision/install_couchbase_server.py, line 42 \[r1\]](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/575#-KLcswbcYdmk5B_jCUy4:-KLcswbcYdmk5B_jCUy5:-275710904) ([raw file](https://github.com/couchbaselabs/mobile-testkit/blob/c699d7752b5a4c92086a87fe49f824e42aeca1a9/libraries/provision/install_couchbase_server.py#L42)):*
> ```Python
>         if self.version.startswith("3.1"):
>             if self.build is None:
>                 base_url = "http://cbmobile-packages.s3.amazonaws.com"
> ```

Might be cleaner to do something like:

```
if self.build is None:
    base_url = "http://cbmobile-packages.s3.amazonaws.com"
else:
    # Look for internal build
    if elif self.version.startswith("4.0") or self.version.startswith("4.1"):
        base_url = "http://cbnas01.sc.couchbase.com/builds/latestbuilds/couchbase-server/sherlock/{}".format(build_for_release)

```

---

*[testsuites/syncgateway/performance/generate_gateload_configs.py, line 89 \[r1\]](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/575#-KLcvOalojxLcsjbYGEE:-KLcvOalojxLcsjbYGEF:1789784730) ([raw file](https://github.com/couchbaselabs/mobile-testkit/blob/c699d7752b5a4c92086a87fe49f824e42aeca1a9/testsuites/syncgateway/performance/generate_gateload_configs.py#L89)):*
> ```Python
> 
>     # Write renderered gateload configs to test results directory
>     with open("testsuites/syncgateway/performance/results/{}/{}.json".format(test_id, gateload_inventory_hostname), "w") as f:
> ```

We could put all this in the `mobile-testkit/results/` dir

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/575)*

**Comment by tleyden** [comment]
Review status: 19 of 23 files reviewed at latest revision, 4 unresolved discussions.

---

*[libraries/provision/generate_pools_json_from_aws.py, line 26 \[r1\]](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/575#-KLcUjoT_S8Aq39qKNlt:-KLw7HzzZoQ0M1P0KlmV:-499146009) ([raw file](https://github.com/couchbaselabs/mobile-testkit/blob/c699d7752b5a4c92086a87fe49f824e42aeca1a9/libraries/provision/generate_pools_json_from_aws.py#L26)):*
<details><summary><i>Previously, sethrosetter (Seth Rosetter) wrote…</i></summary>
> Personally I am a fan of with syntax
> 
> ```
> >>> with open('workfile', 'w') as f:
> ...     f.write("blah")
> >>> f.closed
> True
> ```
</details>
Done.

---

*[libraries/provision/generate_pools_json_from_aws.py, line 69 \[r1\]](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/575#-KLcs-RA6x4N4fvCBv7H:-KLwOo3kOxwmQ-_RyD_q:-499146009) ([raw file](https://github.com/couchbaselabs/mobile-testkit/blob/c699d7752b5a4c92086a87fe49f824e42aeca1a9/libraries/provision/generate_pools_json_from_aws.py#L69)):*
<details><summary><i>Previously, sethrosetter (Seth Rosetter) wrote…</i></summary>
> Can we just put this to 'resources/pool.json' by default or have generate_clusters_from_pool.py take a target pool file? I like the second one more so we could support multiple pool.json files (i.e. pool-aws.json and pool-vagrant.json)
</details>
Done.

---

*[libraries/provision/install_couchbase_server.py, line 42 \[r1\]](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/575#-KLcswbcYdmk5B_jCUy4:-KLwXnJSjUwyv_p0pnQk:1166147455) ([raw file](https://github.com/couchbaselabs/mobile-testkit/blob/c699d7752b5a4c92086a87fe49f824e42aeca1a9/libraries/provision/install_couchbase_server.py#L42)):*
<details><summary><i>Previously, sethrosetter (Seth Rosetter) wrote…</i></summary>
> Might be cleaner to do something like:
> 
> ```
> if self.build is None:
>     base_url = "http://cbmobile-packages.s3.amazonaws.com"
> else:
>     # Look for internal build
>     if elif self.version.startswith("4.0") or self.version.startswith("4.1"):
>         base_url = "http://cbnas01.sc.couchbase.com/builds/latestbuilds/couchbase-server/sherlock/{}".format(build_for_release)
> 
> ```
</details>
Done.  Did some more refactoring to try to make things clearer.

---

*[testsuites/syncgateway/performance/generate_gateload_configs.py, line 89 \[r1\]](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/575#-KLcvOalojxLcsjbYGEE:-KLwZE9-N1OIUpwbcg6D:-171224428) ([raw file](https://github.com/couchbaselabs/mobile-testkit/blob/c699d7752b5a4c92086a87fe49f824e42aeca1a9/testsuites/syncgateway/performance/generate_gateload_configs.py#L89)):*
<details><summary><i>Previously, sethrosetter (Seth Rosetter) wrote…</i></summary>
> We could put all this in the `mobile-testkit/results/` dir
</details>
I looked into this, but this will require changes to quite a few files and requires more cleanup.  How about a separate PR in order to limit scope on this PR?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/575)*

**Comment by sethrosetter** [comment]
Reviewed 1 of 2 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[libraries/provision/generate_pools_json_from_aws.py, line 69 \[r1\]](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/575#-KLcs-RA6x4N4fvCBv7H:-KLwiBy2YBTcxYV1sfgz:-13274069) ([raw file](https://github.com/couchbaselabs/mobile-testkit/blob/c699d7752b5a4c92086a87fe49f824e42aeca1a9/libraries/provision/generate_pools_json_from_aws.py#L69)):*
<details><summary><i>Previously, tleyden (Traun Leyden) wrote…</i></summary>
> Done.
</details>
Added this - https://github.com/couchbaselabs/mobile-testkit/issues/581

---

*[libraries/provision/install_couchbase_server.py, line 85 \[r3\]](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/575#-KLwgyRf-FvC8KD9m-W1:-KLwgyRg0w7BX_XUDhyL:-600199560) ([raw file](https://github.com/couchbaselabs/mobile-testkit/blob/84e58ae61f63dc0c28d6e3303ade3ea472960d24/libraries/provision/install_couchbase_server.py#L85)):*
> ```Python
>         return "http://latestbuilds.hq.couchbase.com/"
>     elif version.startswith("4.0") or version.startswith("4.1"):
>         return "{}/sherlock/{}".format(cbnas_base_url, buildnum_for_release)
> ```


Shouldn't this be `user_specified_build`? You should be able to provide any dev build version here. Or am I confused?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/575)*

**Comment by tleyden** [comment]
Review status: 22 of 23 files reviewed at latest revision, 2 unresolved discussions.

---

*[libraries/provision/install_couchbase_server.py, line 85 \[r3\]](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/575#-KLwgyRf-FvC8KD9m-W1:-KLxBCE-G45YW8pfaidr:1889723848) ([raw file](https://github.com/couchbaselabs/mobile-testkit/blob/84e58ae61f63dc0c28d6e3303ade3ea472960d24/libraries/provision/install_couchbase_server.py#L85)):*
<details><summary><i>Previously, sethrosetter (Seth Rosetter) wrote…</i></summary>
> Shouldn't this be `user_specified_build`? You should be able to provide any dev build version here. Or am I confused?
</details>
Done.  See latest commit .. reworked according to our last chat

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/575)*

**Comment by sethrosetter** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[libraries/provision/install_couchbase_server.py, line 85 \[r3\]](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/575#-KLwgyRf-FvC8KD9m-W1:-KLxECdOOSPChzgzdonP:563631301) ([raw file](https://github.com/couchbaselabs/mobile-testkit/blob/84e58ae61f63dc0c28d6e3303ade3ea472960d24/libraries/provision/install_couchbase_server.py#L85)):*
<details><summary><i>Previously, tleyden (Traun Leyden) wrote…</i></summary>
> Done.  See latest commit .. reworked according to our last chat
</details>
Looks great!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/575)*

**Pull request merged**
