### PR TITLE
Update requirements.txt

### PR DESCRIPTION
**Pull request by borrrden**
Add in an explicit dep for pip to avoid the cryptography pip package compilation madness

### CODE REVIEW

**Comment by tleyden** [comment]
This feels odd to me since I thought pip was installing these requirements in the first place

**Comment by tleyden** [comment]
@borrrden do you have any more details on the cryptography pip package compilation madness?  It feels weird to me to `pip install pip`, and I think we might be better off in the long run if we can avoid it.  Or maybe that's an accepted practice with `virtualenv`, in which case nevermind and we should just merge this.

**Comment by borrrden** [comment]
The goal is to get a certain version of pip as the minimum. This was the command that was recommended by pip itself.

**Comment by borrrden** [comment]
This was actually solved by @sethrosetter 's suggestion of running `pip install --upgrade virtualenv` from outside the virtual environment

**Comment by sethrosetter** [comment]
@borrrden Can I close this then?

**Comment by borrrden** [comment]
Yes, allow me.

**Pull request closed without merging**
