### PR TITLE
Refactor SG functional tests to run in channel cache / distributed index

### LINKED ISSUE #726: Add Couchbase Server 4.5.1 binary to provisioning

### LINKED ISSUE #764: sync_gateway functional test reorg (stage 1)
## Stage one (Requirement for 1.4)
- [x] Tag outlier tests
- [x] run all other tests in channel cache / di mode
- [x] base_cc config (1sg_1cbs, first pass channel cache, second pass di)
- [x] base_di config (1sg_1ac_1cbs, first pass channel cache, second pass di)
- [x] reduce code duplication of bootstrapping
- [x] mode flag in runner (could involve tagging parameterization of test)

```
pytest  -s \
        --pdb \
        --mode=cc \
        --server-version=4.5.1-2844 \
        --sync-gateway-version=1.4.0-16 \
        testsuites/syncgateway/functional/
```

### LINKED ISSUE #772: Update compression tests
Failing to due go improving
- [x] in +- 10 % expected range

### PR DESCRIPTION
**Pull request by sethrosetter**
TODO before merge
- [x] jenkins jobs for cc, di, topology specific
- [x] disable overloaded channel cache for di

Fixes #772 
Fixes #726
Fixes #764 

Enhancements
- One provision at beginning of running tests
- Uniform reset, all tests must provide a SG config and perform a reset
- Remove python path madness by full qualifying the the imports
- Unit tests for config resolution based on mode

TODO post merge
- [ ] Outstanding failures on DI. Bug - https://github.com/couchbase/sync_gateway/issues/2166
- [ ] Update new jobs to point to master

### CODE REVIEW

**Comment by tleyden** [comment]
@sethrosetter can you add links to the current jenkins jobs that use this branch?

**Comment by sethrosetter** [comment]
- http://uberjenkins.sc.couchbase.com/job/cen7-sync-gateway-functional-tests-base-cc/
- http://uberjenkins.sc.couchbase.com/job/cen7-sync-gateway-functional-tests-base-di/
- http://uberjenkins.sc.couchbase.com/job/cen7-sync-gateway-functional-tests-topology-specific/

There is 1 test failure on cc. Digging in. I think I have a theory. This should not block the PR. There are a few on di. These are due to a bug in Sync Gateway

**Comment by tleyden** [comment]
@sethrosetter can you update the instructions on how to run the tests but skipping the provisioning step? I believe this PR adds that ability ..

**Comment by tleyden** [comment]
I tried running a single test according to the README and got errors:

https://gist.github.com/tleyden/9566ba7cf9d803b1ef3e6b1beca613a2

Does the README need to get updated?  Or did I do something wrong?

This is on my local vagrant cluster.

**Comment by tleyden** [comment]
I got the same error when trying to run the whole suite with:

```
pytest  -s --server-version=4.5.1  --sync-gateway-version=1.3.1-16         testsuites/syncgateway/functional/
```

Error:

https://gist.github.com/tleyden/79c7b263660d5f5bcc13ca485f001dcb

**Comment by tleyden** [comment]
I tried running the sgload perf tests with:

```
$ python testsuites/syncgateway/performance/run_sgload_perf_test.py gateload --createreaders --createwriters --numreaders 10 --numwriters 10 --numupdaters 10 --numrevsperdoc 2 --numdocs 100 --numchannels 2 --expvarprogressenabled
Traceback (most recent call last):
  File "testsuites/syncgateway/performance/run_sgload_perf_test.py", line 11, in <module>
    from provision.ansible_runner import AnsibleRunner
ImportError: No module named provision.ansible_runner
```

Is this due to PYTHONPATH changes?  

My PYTHONPATH is currently:

```
$ echo $PYTHONPATH
:/Users/tleyden/Development/mobile-testkit:/Users/tleyden/Development/mobile-testkit/
```

Also, will we need to update the `PYTHONPATH` for the [perf test jenkins job](http://uberjenkins.sc.couchbase.com/view/Performance/job/sync-gateway-perf-test)?  Or is this strictly optional?

**Comment by tleyden** [comment]
The perf test jenkins job is pointing directly to a hardcoded SYNC_GATEWAY_CONFIG_PATH -- if this got renamed, then this will probably break.

I kicked off a few test runs against this branch:

http://uberjenkins.sc.couchbase.com/view/Performance/job/sync-gateway-perf-test/113/
http://uberjenkins.sc.couchbase.com/view/Performance/job/sync-gateway-perf-test/114/

**Comment by sethrosetter** [comment]
Oh good catch. I think the imports on the perf test may have to be updated.

**Comment by tleyden** [comment]
Passing perf test against this branch: http://uberjenkins.sc.couchbase.com/view/Performance/job/sync-gateway-perf-test/118/

**Pull request merged**
