### PR TITLE
Fix Complex Replication Revs Limit Test / Add Pull Replication Auto Pruning test

### PR DESCRIPTION
**Pull request by sethrosetter**
- add Stop Replication keyword
- add Autopruning pull replication test for - https://github.com/couchbase/couchbase-lite-java-core/issues/1319
- Add update delay to revs limit test to avoid push race where the client is exceeding the revs limit before being able to push causing potential conflicts in sync_gateway

---
This change is [Reviewable](https://reviewable.io/reviews/couchbaselabs/mobile-testkit/577)

### CODE REVIEW

**Comment by tleyden** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[keywords/MobileRestClient.py, line 707 \[r1\]](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/577#-KLwb9pYlZiBPOHrjL0F:-KLwb9pYlZiBPOHrjL0G:-1781109493) ([raw file](https://github.com/couchbaselabs/mobile-testkit/blob/13d3817e03b92fc1f8947c6547ebbf63d46d2043/keywords/MobileRestClient.py#L707)):*
> ```Python
>                 continue
> 
>     def update_docs(self, url, db, docs, number_updates, delay=None, auth=None):
> ```

Can you add some docs which explain why the delay is required?  (so that hopefully one day it can be replaced by a more event-based approach)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/577)*

**Comment by sethrosetter** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[keywords/MobileRestClient.py, line 707 \[r1\]](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/577#-KLwb9pYlZiBPOHrjL0F:-KLwdFMYG8t_pRT0K0lt:1384046313) ([raw file](https://github.com/couchbaselabs/mobile-testkit/blob/13d3817e03b92fc1f8947c6547ebbf63d46d2043/keywords/MobileRestClient.py#L707)):*
<details><summary><i>Previously, tleyden (Traun Leyden) wrote…</i></summary>
> Can you add some docs which explain why the delay is required?  (so that hopefully one day it can be replaced by a more event-based approach)
</details>
This issues right here sums it up. https://github.com/couchbase/couchbase-lite-ios/issues/1277. Basically, if your revs depth is small and someone is updating a doc  past the revs depth before a push replication, the push replication will have no common ancestor with sync_gateway causing conflicts to be created. Adding a delay between updates helps this situation. There is an alternative for CBL mac and CBL NET to change the default revs client depth, but that is not configurable for Android. Currently adding a delay will allow the replication to act as expected for all platforms now.  

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/577)*

**Comment by tleyden** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[keywords/MobileRestClient.py, line 707 \[r1\]](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/577#-KLwb9pYlZiBPOHrjL0F:-KLx3AQKHytk9TDhETSJ:2069687377) ([raw file](https://github.com/couchbaselabs/mobile-testkit/blob/13d3817e03b92fc1f8947c6547ebbf63d46d2043/keywords/MobileRestClient.py#L707)):*
<details><summary><i>Previously, sethrosetter (Seth Rosetter) wrote…</i></summary>
> This issues right here sums it up. https://github.com/couchbase/couchbase-lite-ios/issues/1277. Basically, if your revs depth is small and someone is updating a doc  past the revs depth before a push replication, the push replication will have no common ancestor with sync_gateway causing conflicts to be created. Adding a delay between updates helps this situation. There is an alternative for CBL mac and CBL NET to change the default revs client depth, but that is not configurable for Android. Currently adding a delay will allow the replication to act as expected for all platforms now.  
</details>
Ok makes sense.  Can you add a comment to the code to that effect?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/577)*

**Comment by tleyden** [comment]
> Can you add a comment to the code to that effect?

I went ahead and merged this to unblock you, just add the comment directly to the master branch

**Pull request merged**
