### PR TITLE
Feature/implement stale index rev

### LINKED ISSUE #505: Implement unimplemented/test_view_indexing.robot
https://github.com/couchbaselabs/mobile-testkit/blob/master/unimplemented/test_view_indexing.robot

### PR DESCRIPTION
**Pull request by sethrosetter**
- Clean up REST api in MobileRestClient (review carefully)
- Add view_indexing.robot test (Closes #505)
- Add support for view / design docs
- Add 1cbs cluster def
- Add Clean Cluster to client_sg test setup

---
This change is [Reviewable](https://reviewable.io/reviews/couchbaselabs/mobile-testkit/522)

### CODE REVIEW

**Comment by tleyden** [comment]
Review status: 0 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[keywords/MobileRestClient.py, line 998 \[r1\]](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/522#-KKF5wkqTUkUaVZis4wg:-KKF5wkqTUkUaVZis4wh:-1146051797) ([raw file](https://github.com/couchbaselabs/mobile-testkit/blob/e43e240a51528d6f8ccd3a88aa6c7c900bb8c947/keywords/MobileRestClient.py#L998)):*
> ```Python
> 
>     def add_design_doc(self, url, db, name, view):
>         resp = self._session.put("{}/{}/_design/{}".format(url, db, name), data=view)
> ```

Add docs:

```
Keyword that adds a Design Doc to the database


```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/522)*

**Comment by tleyden** [comment]
Review status: 0 of 9 files reviewed at latest revision, 2 unresolved discussions.

---

*[keywords/MobileRestClient.py, line 84 \[r1\]](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/522#-KKF7Km_xDzGifLGutVy:-KKF7Km_xDzGifLGutVz:1965985587) ([raw file](https://github.com/couchbaselabs/mobile-testkit/blob/e43e240a51528d6f8ccd3a88aa6c7c900bb8c947/keywords/MobileRestClient.py#L84)):*
> ```Python
>         self._session.headers = headers
> 
>     def merge(self, *doc_lists):
> ```

Add docs like:

```
Merges these lists into a flat list, eg:

[foo, bar, baz] + [blah, blah2] results in [foo, bar, baz, blah, blah2]

```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/522)*

**Comment by tleyden** [comment]
*[keywords/MobileRestClient.py, line 1027 \[r1\]](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/522#-KKFERk52xgLi-VU0TNb:-KKFERk6_yN5dTRXRAc7:-177436341) ([raw file](https://github.com/couchbaselabs/mobile-testkit/blob/e43e240a51528d6f8ccd3a88aa6c7c900bb8c947/keywords/MobileRestClient.py#L1027)):*
> ```Python
>         logging.debug(keys)
> 
>         assert len(view_response["rows"]) == len(keys), "More rows were returned than expected keys"
> ```

Can you say "different number of rows" instead of "more rows" here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/522)*

**Comment by tleyden** [comment]
*[keywords/MobileRestClient.py, line 1038 \[r1\]](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/522#-KKFE_uY0O7e4z7U5Fro:-KKFE_uY0O7e4z7U5Frp:-177436341) ([raw file](https://github.com/couchbaselabs/mobile-testkit/blob/e43e240a51528d6f8ccd3a88aa6c7c900bb8c947/keywords/MobileRestClient.py#L1038)):*
> ```Python
>         logging.debug(values)
> 
>         assert len(view_response["rows"]) == len(values), "More rows were returned than expected values"
> ```

Can you say "different number of rows" instead of "more rows" here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/522)*

**Comment by tleyden** [comment]
*[keywords/MobileRestClient.py, line 906 \[r1\]](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/522#-KKFHAzlOODRzMWqtwHR:-KKFHAzlOODRzMWqtwHS:1412887758) ([raw file](https://github.com/couchbaselabs/mobile-testkit/blob/e43e240a51528d6f8ccd3a88aa6c7c900bb8c947/keywords/MobileRestClient.py#L906)):*
> ```Python
>             # Issue the request again, docs my still be replicating
>             if not all_docs_returned:
>                 logging.info("Retrying ...")
> ```

Can you change to `Retrying to verify that all docs are present`?  

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/522)*

**Comment by sethrosetter** [comment]
Review status: 0 of 9 files reviewed at latest revision, 5 unresolved discussions.

---

*[keywords/MobileRestClient.py, line 84 \[r1\]](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/522#-KKF7Km_xDzGifLGutVy:-KKFYKsKXJvjOus_yAx4:-499146009) ([raw file](https://github.com/couchbaselabs/mobile-testkit/blob/e43e240a51528d6f8ccd3a88aa6c7c900bb8c947/keywords/MobileRestClient.py#L84)):*
<details><summary><i>Previously, tleyden (Traun Leyden) wrote…</i></summary>
> Add docs like:
> 
> ```
> Merges these lists into a flat list, eg:
> 
> [foo, bar, baz] + [blah, blah2] results in [foo, bar, baz, blah, blah2]
> 
> ```
</details>
Done.

---

*[keywords/MobileRestClient.py, line 906 \[r1\]](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/522#-KKFHAzlOODRzMWqtwHR:-KKFYUIrvfVIZdtYtqh2:-499146009) ([raw file](https://github.com/couchbaselabs/mobile-testkit/blob/e43e240a51528d6f8ccd3a88aa6c7c900bb8c947/keywords/MobileRestClient.py#L906)):*
<details><summary><i>Previously, tleyden (Traun Leyden) wrote…</i></summary>
> Can you change to `Retrying to verify that all docs are present`?  
</details>
Done.

---

*[keywords/MobileRestClient.py, line 998 \[r1\]](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/522#-KKF5wkqTUkUaVZis4wg:-KKFZQQiUbXGY81V1IH8:-499146009) ([raw file](https://github.com/couchbaselabs/mobile-testkit/blob/e43e240a51528d6f8ccd3a88aa6c7c900bb8c947/keywords/MobileRestClient.py#L998)):*
<details><summary><i>Previously, tleyden (Traun Leyden) wrote…</i></summary>
> Add docs:
> 
> ```
> Keyword that adds a Design Doc to the database
> 
> 
> ```
</details>
Done.

---

*[keywords/MobileRestClient.py, line 1027 \[r1\]](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/522#-KKFERk52xgLi-VU0TNb:-KKFZPa-vEa9-9zCWJuP:-499146009) ([raw file](https://github.com/couchbaselabs/mobile-testkit/blob/e43e240a51528d6f8ccd3a88aa6c7c900bb8c947/keywords/MobileRestClient.py#L1027)):*
<details><summary><i>Previously, tleyden (Traun Leyden) wrote…</i></summary>
> Can you say "different number of rows" instead of "more rows" here?
</details>
Done.

---

*[keywords/MobileRestClient.py, line 1038 \[r1\]](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/522#-KKFE_uY0O7e4z7U5Fro:-KKFZP5xqCRYaTVFryfw:-499146009) ([raw file](https://github.com/couchbaselabs/mobile-testkit/blob/e43e240a51528d6f8ccd3a88aa6c7c900bb8c947/keywords/MobileRestClient.py#L1038)):*
<details><summary><i>Previously, tleyden (Traun Leyden) wrote…</i></summary>
> Can you say "different number of rows" instead of "more rows" here?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/522)*

**Comment by tleyden** [comment]
Reviewed 1 of 1 files at r2.
Review status: 1 of 9 files reviewed at latest revision, 2 unresolved discussions.

---

*[keywords/MobileRestClient.py, line 1025 \[r1\]](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/522#-KKFP5aESXPA3uNA9Dcf:-KKFP5aESXPA3uNA9Dcg:-268286518) ([raw file](https://github.com/couchbaselabs/mobile-testkit/blob/e43e240a51528d6f8ccd3a88aa6c7c900bb8c947/keywords/MobileRestClient.py#L1025)):*
> ```Python
>             keys = [keys]
> 
>         logging.debug(keys)
> ```

Can you remove this or at least prepend `verify_view_contains_keys called with keys`

---

*[keywords/MobileRestClient.py, line 1036 \[r1\]](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/522#-KKFPJW6NxF61BBvYUce:-KKFPJW6NxF61BBvYUcf:-1027698166) ([raw file](https://github.com/couchbaselabs/mobile-testkit/blob/e43e240a51528d6f8ccd3a88aa6c7c900bb8c947/keywords/MobileRestClient.py#L1036)):*
> ```Python
>             values = [values]
> 
>         logging.debug(values)
> ```

Can you remove this or at least prepend `verify_view_contains_vals called with vals`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/522)*

**Comment by sethrosetter** [comment]
Review status: 0 of 9 files reviewed at latest revision, 2 unresolved discussions.

---

*[keywords/MobileRestClient.py, line 1025 \[r1\]](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/522#-KKFP5aESXPA3uNA9Dcf:-KKGiVd4U7NY7GxLtJoA:-340781049) ([raw file](https://github.com/couchbaselabs/mobile-testkit/blob/e43e240a51528d6f8ccd3a88aa6c7c900bb8c947/keywords/MobileRestClient.py#L1025)):*
<details><summary><i>Previously, tleyden (Traun Leyden) wrote…</i></summary>
> Can you remove this or at least prepend `verify_view_contains_keys called with keys`
</details>
Done. Removed

---

*[keywords/MobileRestClient.py, line 1036 \[r1\]](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/522#-KKFPJW6NxF61BBvYUce:-KKGiW4saxHejVbuUe5E:-340781049) ([raw file](https://github.com/couchbaselabs/mobile-testkit/blob/e43e240a51528d6f8ccd3a88aa6c7c900bb8c947/keywords/MobileRestClient.py#L1036)):*
<details><summary><i>Previously, tleyden (Traun Leyden) wrote…</i></summary>
> Can you remove this or at least prepend `verify_view_contains_vals called with vals`
</details>
Done. Removed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/522)*

**Comment by tleyden** [comment]
Reviewed 8 of 9 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/522)*

**Pull request merged**
