### PR TITLE
Feature/test multiple replicators

### LINKED ISSUE #630: Create functional test for Long Poll termination request
https://github.com/couchbase/couchbase-lite-java-core/issues/1296

Scenario(s)
## 1
- Create 30 longpoll _changes in a loop (with `timeout` parameter = 5s)
    - Cancel the request after 2s
    - Wait 5.1s
- Create another request `GET /db/` on listener and make sure the listener responds 

## 2
- Create 30 longpoll _changes in a loop (with `heartbeat` parameter = 5s)
    - Cancel the request after 2s
    - Wait 5.1s
- Create another request `GET /db/` on listener and make sure the listener responds

### LINKED ISSUE #632: Create functional test to simultaneously start multiple of the same replicators.
Steps:
1. Setup SGW with a database such as db
2. Create a local database such as db
3. Start 5 continuous push replicators with the exact same properties (e.g. same source and target) by using POST /_replicate
4. Make sure that the same session id returned from POST /_replicate.
5. Check the active tasks (GET /_active_tasks) and make sure there is only 1 task created.
6. Stop the replicator by POST /_replicate with cancel=true.
7. Repeat Step 3-6 by starting pull replicators instead.

### LINKED ISSUE #633: Create functional test to start multiple replicators with different properties
1. Setup SGW with a remote database name db for an example
2. Create a local database such as db
3. Send POST /_replicate with source = db, target = <SGW DB>, continuous = true
4. Send POST /_replicate with source = db, target = <SGW DB>, continuous = true, doc_ids=["doc1", "doc2"]
5. Send POST /_replicate with source = db, target = <SGW DB>, continuous = true, filter="filter1"
6. Make sure that the session_id from each POST /_replicate are different.
7. Send GET /_active_tasks to make sure that there are 3 tasks created.
8. Send 3 POST /_replicate withe the same parameter as Step 3=5 plus cancel=true to stop those replicators
9. Repeat Step 3 - 8 with source = <SGW DB> and target = db for testing the pull replicator.

### LINKED ISSUE #641: Add Test Replication with Session cookie
I think it's a good idea to add this test to the functional tests as we don't have the unit test and the unit test cannot test this easily.

Setup:

1. SyncGateway Config with guest disabled = true and One user added (e.g. user1 / 1234).

Steps:

1. Create a new session on SGW for the user1 by using POST /_session. Capture the SyncGatewaySession cookie from the set-cookie in the response header.

2. Start continuous push and pull replicator on the LiteServ with SyncGatewaySession cookie. Make sure that both replicators start correctly.

 Sample POST /_replicate body:
 ```
// Push
{
      source: 'db',
      target: {
            url: 'http://10.17.2.133:4984/db',
            headers: {
                    Cookie: 'SyncGatewaySession=d92f44b908b5c9dd20b351fb4b8a6b273433387b; Path=/sync_gateway; Expires=Thu, 11 Aug 2016 17:53:49 GMT'
            } 
      },
      continuous: true
}
// Pull
{
      target: 'db',
      source: {
            url: 'http://10.17.2.133:4984/db',
            headers: {
                    Cookie: 'SyncGatewaySession=d92f44b908b5c9dd20b351fb4b8a6b273433387b; Path=/sync_gateway; Expires=Thu, 11 Aug 2016 17:53:49 GMT'
            } 
      },
      continuous: true
}
```
Note that I don't know if Path and Expires are required or not.

3. Delete the session from SGW by sending DELETE /_sessions/<sessionid> to SGW.

4. Cancel both push and pull replicator on the LiteServ.

5. Repeat step 1 and 2.

Reference: https://github.com/couchbase/couchbase-lite-android/issues/817.

### PR DESCRIPTION
**Pull request by sethrosetter**
- Ignore ansible *.retry files
- add breakpoint() method for debugging native python when running under robot
- changes_tracker.start() now supports timeout / heartbeat / request_timeout
- Fixes #632 
- Fixes #633 
- Fixes #641 
- Fixes #630 
- Add support for provisioning SQLite / Other platforms for Android .apks
- Add `get_session`,  `request_session`, `get_database`, `get_databases`
- Add support for auth and filters for `start_replication` and `stop_replication` keywords
- Add support for provisioning CBS `4.6` Sync Gateway `1.3.1`

---
This change is [Reviewable](https://reviewable.io/reviews/couchbaselabs/mobile-testkit/650)

### CODE REVIEW

**Comment by sethrosetter** [comment]
Kicked off the following jobs
- [ ] http://uberjenkins.sc.couchbase.com/job/android-listener-client-sync-gateway/68/
- [ ] http://uberjenkins.sc.couchbase.com/job/macosx-listener-client-sync-gateway/94/
- [ ] http://uberjenkins.sc.couchbase.com/job/net-listener-client-sync-gateway/94/

**Comment by sethrosetter** [comment]
https://github.com/couchbase/couchbase-lite-ios/issues/1236 will cause Long Poll Changes Timeout and Longpoll Changes Heartbeat to fail on Mac OSX

---

Review status: 0 of 23 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/650#-:-KQMVNmJ_qlaDciXU3-I:bh8gjmr)*

**Comment by tleyden** [comment]
Review status: 0 of 23 files reviewed at latest revision, 2 unresolved discussions.

---

*[testsuites/listener/shared/client_sg/listener_changes.py, line 63 \[r1\]](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/650#-KQMW-gOLcWAskFumqf8:-KQMW-gOLcWAskFumqf9:b-lcmptd) ([raw file](https://github.com/couchbaselabs/mobile-testkit/blob/080ec3dc40933f9f913bf61bd35de8e12712101c/testsuites/listener/shared/client_sg/listener_changes.py#L63)):*
> ```Python
>         ) for _ in range(30)]
> 
>     log_info("Futures exited")
> ```

Delete this log at the minimum -- might be a bug somewhere .   Need some way to block on future completion.  Otherwise, test might be negated.

Call AsCompleted on all the futures.

---

*[testsuites/listener/shared/client_sg/listener_replication.robot, line 36 \[r1\]](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/650#-KQMZn0OwBUnLim1KcEo:-KQMZn0OwBUnLim1KcEp:bgm2nv3) ([raw file](https://github.com/couchbaselabs/mobile-testkit/blob/080ec3dc40933f9f913bf61bd35de8e12712101c/testsuites/listener/shared/client_sg/listener_replication.robot#L36)):*
> ```RobotFramework
>     ...  Referenced issue: couchbase/couchbase-lite-android#955.
>     Start Sync Gateway  url=${sg_url}  config=${SYNC_GATEWAY_CONFIGS}/walrus.json
>     Large Initial Pull Replication
> ```

Can this be renamed to just "Pull Replication" -- would that make it more re-usable?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/650)*

**Comment by sethrosetter** [comment]
Review status: 0 of 23 files reviewed at latest revision, 2 unresolved discussions.

---

*[testsuites/listener/shared/client_sg/listener_changes.py, line 63 \[r1\]](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/650#-KQMW-gOLcWAskFumqf8:-KQM_LctJ3TynwU30wZv:b-896fix) ([raw file](https://github.com/couchbaselabs/mobile-testkit/blob/080ec3dc40933f9f913bf61bd35de8e12712101c/testsuites/listener/shared/client_sg/listener_changes.py#L63)):*
<details><summary><i>Previously, tleyden (Traun Leyden) wrote…</i></summary>
> Delete this log at the minimum -- might be a bug somewhere .   Need some way to block on future completion.  Otherwise, test might be negated.
> 
> Call AsCompleted on all the futures.
</details>
Done.

---

*[testsuites/listener/shared/client_sg/listener_replication.robot, line 36 \[r1\]](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/650#-KQMZn0OwBUnLim1KcEo:-KQM_J9mkHvQxAUdW1Hz:be55u6v) ([raw file](https://github.com/couchbaselabs/mobile-testkit/blob/080ec3dc40933f9f913bf61bd35de8e12712101c/testsuites/listener/shared/client_sg/listener_replication.robot#L36)):*
<details><summary><i>Previously, tleyden (Traun Leyden) wrote…</i></summary>
> Can this be renamed to just "Pull Replication" -- would that make it more re-usable?
</details>
The "Initial" is hinting at a pull of a preseeded database. The flow is: preseed a sync_gateway db, issue one shot or continuous pull, verify all the docs replicated. I think "Pull replication" may be too general. These are meant to test a initial replication. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/650)*

**Comment by tleyden** [comment]
Review status: 0 of 23 files reviewed at latest revision, 5 unresolved discussions.

---

*[testsuites/listener/shared/client_sg/listener_replication.py, line 34 \[r1\]](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/650#-KQM_m6mtOOu1YJi-LyP:-KQM_m6mtOOu1YJi-LyQ:b-95lqn5) ([raw file](https://github.com/couchbaselabs/mobile-testkit/blob/080ec3dc40933f9f913bf61bd35de8e12712101c/testsuites/listener/shared/client_sg/listener_replication.py#L34)):*
> ```Python
>     session = client.create_session(sg_one_admin, sg_db, "seth")
> 
>     # Create 10000 docs on sync_gateway
> ```

Should this be "Create num_docs docs on sync gateway"?

---

*[testsuites/listener/shared/client_sg/listener_replication.py, line 89 \[r1\]](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/650#-KQMaGg0vemdYSmSOLiw:-KQMaGg0vemdYSmSOLix:bueo57l) ([raw file](https://github.com/couchbaselabs/mobile-testkit/blob/080ec3dc40933f9f913bf61bd35de8e12712101c/testsuites/listener/shared/client_sg/listener_replication.py#L89)):*
> ```Python
> 
> def large_initial_push_replication(ls_url, cluster_config, num_docs, continuous):
> ```

There's a lot of code duplication between large_initial_push_replication and large_initial_pull_replication.

What about keeping these method signature, but factoring out the common code into `large_initial_replication` which takes the source db and target db as params?

---

*[testsuites/listener/shared/client_sg/listener_replication.py, line 211 \[r1\]](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/650#-KQMaqajzGlSWKaRrc04:-KQMaqak8Ww8QVZgzZAB:bis39zv) ([raw file](https://github.com/couchbaselabs/mobile-testkit/blob/080ec3dc40933f9f913bf61bd35de8e12712101c/testsuites/listener/shared/client_sg/listener_replication.py#L211)):*
> ```Python
> 
>     # Global var gets incremented according to Pasin.
>     repl_id = "repl052"
> ```

this is confusing .. how was `repl052` derived?  any simpler way to accomplish this?  or maybe we can make other assertions about the future.result() values without having to hardcode a particular number?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/650)*

**Comment by tleyden** [comment]
Review status: 0 of 23 files reviewed at latest revision, 6 unresolved discussions.

---

*[testsuites/listener/shared/client_sg/listener_replication.py, line 368 \[r1\]](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/650#-KQMcIxj50fmCtiReIJ8:-KQMcIxj50fmCtiReIJ9:b-pfz83j) ([raw file](https://github.com/couchbaselabs/mobile-testkit/blob/080ec3dc40933f9f913bf61bd35de8e12712101c/testsuites/listener/shared/client_sg/listener_replication.py#L368)):*
> ```Python
>         to_db=ls_db
>     )
>     assert repl_seven == "repl007", "Replication {} should have id: repl007".format(repl_seven)
> ```

Is it possible to make the same assertion without the hardcoded ID?  Maybe just assert that it's greater than the last one?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/650)*

**Comment by sethrosetter** [comment]
Review status: 0 of 23 files reviewed at latest revision, 5 unresolved discussions.

---

*[testsuites/listener/shared/client_sg/listener_replication.py, line 34 \[r1\]](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/650#-KQM_m6mtOOu1YJi-LyP:-KQNRNDZDmd_sqiTwj-d:b-896fix) ([raw file](https://github.com/couchbaselabs/mobile-testkit/blob/080ec3dc40933f9f913bf61bd35de8e12712101c/testsuites/listener/shared/client_sg/listener_replication.py#L34)):*
<details><summary><i>Previously, tleyden (Traun Leyden) wrote…</i></summary>
> Should this be "Create num_docs docs on sync gateway"?
</details>
Done.

---

*[testsuites/listener/shared/client_sg/listener_replication.py, line 89 \[r1\]](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/650#-KQMaGg0vemdYSmSOLiw:-KQNRNhB_IM8Cbj5Auuc:b-y1uraz) ([raw file](https://github.com/couchbaselabs/mobile-testkit/blob/080ec3dc40933f9f913bf61bd35de8e12712101c/testsuites/listener/shared/client_sg/listener_replication.py#L89)):*
<details><summary><i>Previously, tleyden (Traun Leyden) wrote…</i></summary>
> There's a lot of code duplication between large_initial_push_replication and large_initial_pull_replication.
> 
> What about keeping these method signature, but factoring out the common code into `large_initial_replication` which takes the source db and target db as params?
</details>
Its true. I could factor out the source and target and turn it into one. There are subtleties beside the replication call like where docs are seeded and what endpoint is validated. If you still think it should be done, I can do it. 

---

*[testsuites/listener/shared/client_sg/listener_replication.py, line 211 \[r1\]](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/650#-KQMaqajzGlSWKaRrc04:-KQNQYjs5XWMPKBWDyop:b-896fix) ([raw file](https://github.com/couchbaselabs/mobile-testkit/blob/080ec3dc40933f9f913bf61bd35de8e12712101c/testsuites/listener/shared/client_sg/listener_replication.py#L211)):*
<details><summary><i>Previously, tleyden (Traun Leyden) wrote…</i></summary>
> this is confusing .. how was `repl052` derived?  any simpler way to accomplish this?  or maybe we can make other assertions about the future.result() values without having to hardcode a particular number?
</details>
Done.

---

*[testsuites/listener/shared/client_sg/listener_replication.py, line 368 \[r1\]](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/650#-KQMcIxj50fmCtiReIJ8:-KQNTQwFuHbKZlIpKBsF:b-896fix) ([raw file](https://github.com/couchbaselabs/mobile-testkit/blob/080ec3dc40933f9f913bf61bd35de8e12712101c/testsuites/listener/shared/client_sg/listener_replication.py#L368)):*
<details><summary><i>Previously, tleyden (Traun Leyden) wrote…</i></summary>
> Is it possible to make the same assertion without the hardcoded ID?  Maybe just assert that it's greater than the last one?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/650)*

**Comment by tleyden** [comment]
Review status: 0 of 22 files reviewed at latest revision, 2 unresolved discussions.

---

*[testsuites/listener/shared/client_sg/listener_replication.robot, line 36 \[r1\]](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/650#-KQMZn0OwBUnLim1KcEo:-KQN5kReqHZ1RCGdYVSW:brakbn7) ([raw file](https://github.com/couchbaselabs/mobile-testkit/blob/080ec3dc40933f9f913bf61bd35de8e12712101c/testsuites/listener/shared/client_sg/listener_replication.robot#L36)):*
<details><summary><i>Previously, sethrosetter (Seth Rosetter) wrote…</i></summary>
> The "Initial" is hinting at a pull of a preseeded database. The flow is: preseed a sync_gateway db, issue one shot or continuous pull, verify all the docs replicated. I think "Pull replication" may be too general. These are meant to test a initial replication. 
</details>
Ok what about "Initial Pull Replication"?  Especially since the size is a parameter.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/650)*

**Comment by sethrosetter** [comment]
Review status: 0 of 22 files reviewed at latest revision, 1 unresolved discussion.

---

*[testsuites/listener/shared/client_sg/listener_replication.robot, line 36 \[r1\]](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/650#-KQMZn0OwBUnLim1KcEo:-KQNWOc4IlPNV8HSBaSC:b-896fix) ([raw file](https://github.com/couchbaselabs/mobile-testkit/blob/080ec3dc40933f9f913bf61bd35de8e12712101c/testsuites/listener/shared/client_sg/listener_replication.robot#L36)):*
<details><summary><i>Previously, tleyden (Traun Leyden) wrote…</i></summary>
> Ok what about "Initial Pull Replication"?  Especially since the size is a parameter.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/650)*

**Comment by tleyden** [comment]
Reviewed 18 of 23 files at r1, 4 of 4 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/650)*

**Pull request merged**
