### PR TITLE
Feature/sg attachments pt 2

### LINKED ISSUE #458: Implement sg attachment tests
https://github.com/couchbaselabs/mobile-testkit/blob/master/unimplemented/local_sg_cbs.robot

- [x] Test Attachment Revpos When Ancestor Unavailable
- [x] Test Attachment Revpos When Ancestor Unavailable, Active Revision doesn't share ancestor
- [x] Test Attachments on Docs Rejected By Sync Function

### PR DESCRIPTION
**Pull request by sethrosetter**
Fixes #458 
- add `get_server_docs_with_prefix` keyword
- `add conflict` can now take an attachment
- `add conflict` can now take an single parent rev or list of parent revs
- `update doc` can now take an attachment
- Add "Test Attachment Revpos When Ancestor Unavailable, Active Revision doesn't share ancestor" test
- Add "Test Attachments on Docs Rejected By Sync Function"

---
This change is [Reviewable](https://reviewable.io/reviews/couchbaselabs/mobile-testkit/495)

### CODE REVIEW

**Comment by tleyden** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[keywords/CouchbaseServer.py, line 269 \[r1\]](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/495#-KJIedG5-ddJSlV3sDAY:-KJIedG5-ddJSlV3sDAZ:1601260730) ([raw file](https://github.com/couchbaselabs/mobile-testkit/blob/a083fd68d19f840cc4e06f7f9846ef340e6b6e8b/keywords/CouchbaseServer.py#L269)):*
> ```Python
>         b.n1ql_query("CREATE PRIMARY INDEX ON `{}`".format(bucket)).execute()
>         for row in b.n1ql_query("SELECT meta(`{}`) FROM `{}`".format(bucket, bucket)):
>             if row["$1"]["id"].startswith(prefix):
> ```

what is `$1` here?  can that get a more descriptive name? 

---

*[keywords/Document.py, line 30 \[r1\]](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/495#-KJIfNJ9c3PNW0tWGVyy:-KJIfNJ9c3PNW0tWGVyz:-155158028) ([raw file](https://github.com/couchbaselabs/mobile-testkit/blob/a083fd68d19f840cc4e06f7f9846ef340e6b6e8b/keywords/Document.py#L30)):*
> ```Python
>         if attachment is not None:
>             doc["_attachments"] = {
>                 attachment: { "data": get_attachment(attachment) }
> ```

I think this would be clearer as `get_attachment(attachment_name)`

---

*[keywords/MobileRestClient.py, line 483 \[r1\]](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/495#-KJIfdzxgq9UKSpYcyVd:-KJIfdzxgq9UKSpYcyVe:-1706878983) ([raw file](https://github.com/couchbaselabs/mobile-testkit/blob/a083fd68d19f840cc4e06f7f9846ef340e6b6e8b/keywords/MobileRestClient.py#L483)):*
> ```Python
> 
> 
>         parent_revision_digests = [parent_rev.split("-")[1] for parent_rev in parent_revs]
> ```

I think this would be clearer if `parent_rev.split("-")[1]` were factored out into a variable or helper method, with comments on what is happening (eg, split 1-abc into components and grab the abc part).  

---

*[keywords/MobileRestClient.py, line 613 \[r1\]](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/495#-KJIg4IcX1INxDEnR3_q:-KJIg4IcX1INxDEnR3_r:1565489329) ([raw file](https://github.com/couchbaselabs/mobile-testkit/blob/a083fd68d19f840cc4e06f7f9846ef340e6b6e8b/keywords/MobileRestClient.py#L613)):*
> ```Python
>             future_to_url = [executor.submit(self.update_doc, url, db, doc, number_updates, auth) for doc in docs]
>             for future in concurrent.futures.as_completed(future_to_url):
>                 result = future.result()
> ```

I think `update_doc_result = update_doc_future.result()` might be clearer .. albeit a bit longer

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/495)*

**Comment by sethrosetter** [comment]
Review status: 4 of 7 files reviewed at latest revision, 4 unresolved discussions.

---

*[keywords/CouchbaseServer.py, line 269 \[r1\]](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/495#-KJIedG5-ddJSlV3sDAY:-KJIhc8TGcLE6r3ZDAL7:-1725326622) ([raw file](https://github.com/couchbaselabs/mobile-testkit/blob/a083fd68d19f840cc4e06f7f9846ef340e6b6e8b/keywords/CouchbaseServer.py#L269)):*
<details><summary><i>Previously, tleyden (Traun Leyden) wrote…</i></summary>
> what is `$1` here?  can that get a more descriptive name? 
</details>
That "$1" is returned in the response from the N1QL query. There is not much I can do about it.

---

*[keywords/Document.py, line 30 \[r1\]](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/495#-KJIfNJ9c3PNW0tWGVyy:-KJIjOCJRW0COPssOFc-:-497468049) ([raw file](https://github.com/couchbaselabs/mobile-testkit/blob/a083fd68d19f840cc4e06f7f9846ef340e6b6e8b/keywords/Document.py#L30)):*
<details><summary><i>Previously, tleyden (Traun Leyden) wrote…</i></summary>
> I think this would be clearer as `get_attachment(attachment_name)`
</details>
Fixed

---

*[keywords/MobileRestClient.py, line 483 \[r1\]](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/495#-KJIfdzxgq9UKSpYcyVd:-KJInoRbfFGifW8tM_uT:-497468049) ([raw file](https://github.com/couchbaselabs/mobile-testkit/blob/a083fd68d19f840cc4e06f7f9846ef340e6b6e8b/keywords/MobileRestClient.py#L483)):*
<details><summary><i>Previously, tleyden (Traun Leyden) wrote…</i></summary>
> I think this would be clearer if `parent_rev.split("-")[1]` were factored out into a variable or helper method, with comments on what is happening (eg, split 1-abc into components and grab the abc part).  
</details>
Fixed

---

*[keywords/MobileRestClient.py, line 613 \[r1\]](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/495#-KJIg4IcX1INxDEnR3_q:-KJIoDILLtKkGsuqnUD9:-467915377) ([raw file](https://github.com/couchbaselabs/mobile-testkit/blob/a083fd68d19f840cc4e06f7f9846ef340e6b6e8b/keywords/MobileRestClient.py#L613)):*
<details><summary><i>Previously, tleyden (Traun Leyden) wrote…</i></summary>
> I think `update_doc_result = update_doc_future.result()` might be clearer .. albeit a bit longer
</details>
fixed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/495)*

**Comment by tleyden** [comment]
Reviewed 1 of 3 files at r2.
Review status: 5 of 7 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/495)*

**Comment by tleyden** [comment]
Reviewed 2 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/495)*

**Pull request merged**
