### PR TITLE
Feature/add revs pruning test

### LINKED ISSUE #532: Auto Pruning SQLite Tests
Add a robot test that will exceed revs_limit for LiteServ, assert that the limit is respected

### PR DESCRIPTION
**Pull request by sethrosetter**
Fixes #532 - Adds sanity tests for SQLite pruning

- get_conflict_revs Keyword
- wait_for_no_replications Keyword
- Fix a few robot tests
    - Delete conflicts before delete docs to avoid deleted doc reverting to a previous conflicted revision
    - Lower revs to avoid unexpected behavior https://github.com/couchbase/couchbase-lite-ios/issues/1277
    - Add sleep to intermittent failing test in CI, not the best fix but we don't have retry support in the old `user` class

---
This change is [Reviewable](https://reviewable.io/reviews/couchbaselabs/mobile-testkit/537)

### CODE REVIEW

**Comment by tleyden** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[testsuites/syncgateway/functional/test_sync.py, line 380 \[r1\]](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/537#-KKjJibAq2acfqa5Z6hs:-KKjJibB_JA7yGs4Hzly:739209288) ([raw file](https://github.com/couchbaselabs/mobile-testkit/blob/21b9f58ec430f4e27c647c0081c1951cbae28837/testsuites/syncgateway/functional/test_sync.py#L380)):*
> ```Python
>     assert len(read_only_user_docs.items()) == 0
> 
>     # wait, some changes are not instant
> ```

can you be more specific about which changes are not instant?  also, can you mention what would need to happen for this to be "event based" rather than "sleep based", even if it's too much work to do now?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/537)*

**Comment by sethrosetter** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[testsuites/syncgateway/functional/test_sync.py, line 380 \[r1\]](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/537#-KKjJibAq2acfqa5Z6hs:-KKkwvkhjR9WnOeFAVXb:-1235644051) ([raw file](https://github.com/couchbaselabs/mobile-testkit/blob/21b9f58ec430f4e27c647c0081c1951cbae28837/testsuites/syncgateway/functional/test_sync.py#L380)):*
<details><summary><i>Previously, tleyden (Traun Leyden) wrote…</i></summary>
> can you be more specific about which changes are not instant?  also, can you mention what would need to happen for this to be "event based" rather than "sleep based", even if it's too much work to do now?
</details>
It seems be non deterministic but sometimes when issuing the changes call return, some of the documents are returned but not all. There is currently no retry loop and I'm guessing that the bulk_docs requests are still processing.

 For the second point, This is patching an older test. The new robot tests do not have any sleeps but rather poll until a timeout. At the bare minimum, we would have to convert the older get_changes (https://github.com/couchbaselabs/mobile-testkit/blob/master/libraries/testkit/user.py#L369) to try a polling approach if it does not get all of its docs on the first try. This could be a bigger refactor that just that, however.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/537)*

**Comment by tleyden** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[testsuites/syncgateway/functional/test_sync.py, line 380 \[r1\]](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/537#-KKjJibAq2acfqa5Z6hs:-KKnwTmFP6-dY8Rvw4hu:457790100) ([raw file](https://github.com/couchbaselabs/mobile-testkit/blob/21b9f58ec430f4e27c647c0081c1951cbae28837/testsuites/syncgateway/functional/test_sync.py#L380)):*
<details><summary><i>Previously, sethrosetter (Seth Rosetter) wrote…</i></summary>
> It seems be non deterministic but sometimes when issuing the changes call return, some of the documents are returned but not all. There is currently no retry loop and I'm guessing that the bulk_docs requests are still processing.
> 
>  For the second point, This is patching an older test. The new robot tests do not have any sleeps but rather poll until a timeout. At the bare minimum, we would have to convert the older get_changes (https://github.com/couchbaselabs/mobile-testkit/blob/master/libraries/testkit/user.py#L369) to try a polling approach if it does not get all of its docs on the first try. This could be a bigger refactor that just that, however.
</details>
Ok can you add the first paragraph to the comment?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/537)*

**Comment by sethrosetter** [comment]
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[testsuites/syncgateway/functional/test_sync.py, line 380 \[r1\]](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/537#-KKjJibAq2acfqa5Z6hs:-KKoEiVW_yeQxNjGqMWG:-499146009) ([raw file](https://github.com/couchbaselabs/mobile-testkit/blob/21b9f58ec430f4e27c647c0081c1951cbae28837/testsuites/syncgateway/functional/test_sync.py#L380)):*
<details><summary><i>Previously, tleyden (Traun Leyden) wrote…</i></summary>
> Ok can you add the first paragraph to the comment?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/537)*

**Pull request merged**
