### PR TITLE
Add a way to easily run a batch of tests

### PR DESCRIPTION
**Pull request by tleyden**
#### Fixes #.

- [x] Flew under the `flake8` radar 'cuz it's not in the list of files to check
- [ ] Ran `run_repo_tests.sh`

#### Changes proposed in this pull request:

- For my current PR branch I needed a way to isolate the failing tests and run them all with a single script.  This is what I wrote locally, and it seems like something nice to have in the repo in one form or another.

### CODE REVIEW

**Comment by sethrosetter** [comment]
@tleyden Do you want this in?

**Comment by tleyden** [comment]
No I don't think it's ready to go in yet

**Comment by tleyden** [comment]
I put it up for discussion, and did a PR rather than an issue just to have something tangible

**Comment by sethrosetter** [comment]
Closing for now:
A new PR should be opened per convo with @tleyden:
- [ ] Just the scripts, move to folder `local_dev` or something similar
- [ ] Separate data and script `run_subset.py` and `subset_spec.py`

**Comment by tleyden** [comment]
Replaced by https://github.com/couchbaselabs/mobile-testkit/pull/1192

**Pull request closed without merging**
