### PR TITLE
Feature/remove guest user

### LINKED ISSUE #1257: Remove guest user in all SG configs

### PR DESCRIPTION
**Pull request by sethrosetter**
#### Fixes #1257.

- [x] Ran `flake8`
- [x] Ran `run_repo_tests.sh`

#### Changes proposed in this pull request:

- remove guest user from testkit configs. We should be defining actual users via config or Admin rest API

### CODE REVIEW

**Comment by raghusarangapani** [comment]
The changes look ok. It would be great if the changes can be tested on jenkins, if it has not been tested already, before merging.

**Comment by sethrosetter** [comment]
Test run - http://uberjenkins.sc.couchbase.com/job/cen7-sync-gateway-functional-tests-base-cc/739/

**Comment by raghusarangapani** [comment]
There are three failures with this run

**Comment by raghusarangapani** [comment]
ok, 740 looks good

**Pull request merged**
