### PR TITLE
Feature/build sg accel2

### PR DESCRIPTION
**Pull request by tleyden**
Fixes https://github.com/couchbaselabs/mobile-testkit/issues/721

Notes: 

- Related to https://github.com/couchbase/sync_gateway/pull/2122 sg accel build changes
- Requires changes to jenkins jobs that build from source -- so far I've only updated http://uberjenkins.sc.couchbase.com/job/syncgateway-functional-tests-dev/
- The README was changed to document an extra step related to private keys to clone the private github repo

### CODE REVIEW

**Comment by tleyden** [comment]
This should be ready to merge now.

Here is a passing functional test, including provisioning and building sg accel from source:

http://uberjenkins.sc.couchbase.com/job/syncgateway-functional-tests-dev/180/console

(the only thing that failed was the artifact collection)

**Comment by tleyden** [comment]
After this is merged to master, http://uberjenkins.sc.couchbase.com/job/pytest_centos7-mobile-sync-gateway-functional-tests/configure will need to be updated to reflect a few changes in the jenkins job.

### Install deps

```
# Install deps if needed
if [ "$INSTALL_DEPS" == "true" ]; then
  echo "Installing dependencies"
  export CLUSTER_CONFIG=resources/cluster_configs/${TEST_SUITE} 
  python libraries/provision/install_deps.py
  unset CLUSTER_CONFIG
fi

```

### Sg accel github deploy key 

```
# Enable building private sync-gateway-accel repo by making sure that 
# the VM's have the private key that is registered with github as a 
# deploy key on the sync-gateway-accel repo
echo $private_key_base64 | base64 -d > /tmp/private_key
python libraries/utilities/install-gh-deploy-keys.py \
    --key-path=/tmp/private_key \
    --ssh-user=root
```

### Debug / fail on non-zero exit

```
set -x
set -e
```

Not strictly required, but useful to output all shell commands and abort on any non-zero exit code.

**Comment by tleyden** [comment]
Clean jenkins build: http://uberjenkins.sc.couchbase.com/job/syncgateway-functional-tests-dev/183/

**Comment by tleyden** [comment]
I updated the [pytest_centos7-mobile-sync-gateway-functional-test jenkins job](http://uberjenkins.sc.couchbase.com/job/pytest_centos7-mobile-sync-gateway-functional-tests/36/console), and ran a smoke test that is passing.

**Comment by sethrosetter** [comment]
Thanks for doing that!

**Pull request merged**
