### PR TITLE
Cross platform (Android, Mac OSX, NET) Listener + Sync Gateway replication integration test in robot

### LINKED ISSUE #428: Port cbl-replication-mismatch.js to Robot
- [x] Start LiteServ (Mac OSX, Android)
- [x] Start sync_gateway
- [x] Create db1 and db2 on LiteServ
- [x] Setup continuous push / pull to from LiteServ db1 -> sync_gateway db1
- [x] Setup continuous push / pull to from LiteServ db2 -> sync_gateway db1
- [x] Add 500 docs to both LiteServ db1 and db2
- [x] Verify 500 docs in each db
- [x] Verify sync_gateway changes feed has all docs in it
    - [x] Verify _changes against _all_docs
    - [x] Check Num Docs
    - [x] Verify no duplicate ids
    - [x] Verify no duplication sequence numbers
    - [x] Verify no missing changes
- [x] Verify docs in LiteServ db1 and db2
    - [x] Verify _changes against _all_docs
    - [x] Check Num Docs
    - [x] Verify no duplicate ids
    - [x] Verify no duplication sequence numbers
    - [x] Verify no missing changes
    - [x] assert db1 has docs from db1, db2
    - [x] assert db2 has docs from db1, db2

### PR DESCRIPTION
**Pull request by sethrosetter**
Fixes #428 

Adds the following keywords and supporting functionality

### LiteServ
- Download Liteserv
- Get Liteserv Binary Path
- Install Apk
- Launch Activity
- Stop Activity
- Remove Liteserv
- Verify Liteserv Launched  ${host}  ${port}
- (Hack) Start Mono Process  ${path}  ${port}  
- (Hack) Kill Mono Process

### SyncGateway
- Download Sync Gateway
- Remove Sync Gateway
- Get Sync Gateway Binary Path
- Verify Sync Gateway Launched  ${host}  ${port}  ${admin_port}

### TKClient (Xplat between Listener (Mac OSX, Android, NET) and Sync Gateway)
- Get Server Type  ${url}
- Create Database  ${url}  ${name}
- Delete Database  ${url}  ${name}
- Add Docs  ${url}  ${db}  ${number}  ${id_prefix}
- Start Replication  ${url}  ${continuou}  ${from_url}  ${from_db}  ${to_url}  ${to_db}
- Verify Docs Present  ${url}  ${db}  ${expected_docs}
- Verify Docs In Changes  ${url}  ${db}  ${expected_docs}

Known limitations
- mono process keywords https://github.com/couchbaselabs/mobile-testkit/issues/442

---
This change is [Reviewable](https://reviewable.io/reviews/couchbaselabs/mobile-testkit/441)

### CODE REVIEW

**Comment by tleyden** [comment]
@sethrosetter I enabled revievable.io for this repo, and there is now a "reviewable" badge on this PR

**Comment by tleyden** [comment]
*[setup.sh, line 12 \[r2\]](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/441#-KHMCAaRau_KrT5bQH3o:-KHMCAaRau_KrT5bQH3p:1318206429) ([raw file](https://github.com/couchbaselabs/mobile-testkit/blob/ec05e83da3e918fb916b9b1279ea99680e558c39/setup.sh#L12)):*
> ```Shell
> 
> # Setup virtual env
> virtualenv -p /usr/bin/python venv
> ```

Change this to just `python` instead of `/usr/bin/python`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/441)*

**Comment by tleyden** [comment]
Reviewed 26 of 27 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

*[run_listener_tests_android.sh, line 2 \[r2\]](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/441#-KHMAWbkpv6MMH_Z4Mj7:-KHMAWbll9JcCM3xIlF5:-1463492194) ([raw file](https://github.com/couchbaselabs/mobile-testkit/blob/ec05e83da3e918fb916b9b1279ea99680e558c39/run_listener_tests_android.sh#L2)):*
> ```Shell
> #!/usr/bin/env bash
> ```

Take this out of the repo, and add to the README.  (for your local system, you can have a hidden directory)

In readme, add some explanation how users can figure out what values to use for these variables.

---

*[run_listener_tests_macosx.sh, line 2 \[r2\]](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/441#-KHMBMDXyXHynZwV0so0:-KHMBMDY0ffqBOGii6lU:-842521137) ([raw file](https://github.com/couchbaselabs/mobile-testkit/blob/ec05e83da3e918fb916b9b1279ea99680e558c39/run_listener_tests_macosx.sh#L2)):*
> ```Shell
> #!/usr/bin/env bash
> ```

Ditto on other .sh file

---

*[setup.sh, line 1 \[r2\]](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/441#-KHMBeKnKP1Bsiu2muXx:-KHMBeKnKP1Bsiu2muXy:-1625498616) ([raw file](https://github.com/couchbaselabs/mobile-testkit/blob/ec05e83da3e918fb916b9b1279ea99680e558c39/setup.sh#L1)):*
> ```Shell
> # See if virtual env is installed
> ```

The top of this file should have a description of what this is doing at a high level

---

*[setup.sh, line 12 \[r2\]](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/441#-KHMCAaRau_KrT5bQH3o:-KHMCVusQnUavV19at6z:-394566397) ([raw file](https://github.com/couchbaselabs/mobile-testkit/blob/ec05e83da3e918fb916b9b1279ea99680e558c39/setup.sh#L12)):*
<details><summary><i>Previously, tleyden (Traun Leyden) wrote…</i></summary>
> Change this to just `python` instead of `/usr/bin/python`</details>
Just sent this to you proactively

---

*[setup.sh, line 15 \[r2\]](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/441#-KHMByjnECwOWc6L_FhV:-KHMByjnECwOWc6L_FhW:425732133) ([raw file](https://github.com/couchbaselabs/mobile-testkit/blob/ec05e83da3e918fb916b9b1279ea99680e558c39/setup.sh#L15)):*
> ```Shell
> source venv/bin/activate
> 
> # Get python version
> ```

Move this to beginning of script so it's in a weird state

---

*[keywords/Async.py, line 5 \[r2\]](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/441#-KHMCvGXsfB9pjK2zNLf:-KHMCvGYeIs6cbknDBeY:-470473455) ([raw file](https://github.com/couchbaselabs/mobile-testkit/blob/ec05e83da3e918fb916b9b1279ea99680e558c39/keywords/Async.py#L5)):*
> ```Python
> from concurrent.futures import ThreadPoolExecutor
> ```

Add something to the top of the file that says:

* What this does (high level overview)
* That it's experimental and not being used yet

---

*[keywords/SyncGateway.py, line 112 \[r2\]](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/441#-KHMF5YSibDGeKhYq7O8:-KHMF5YSibDGeKhYq7O9:-305723986) ([raw file](https://github.com/couchbaselabs/mobile-testkit/blob/ec05e83da3e918fb916b9b1279ea99680e558c39/keywords/SyncGateway.py#L112)):*
> ```Python
> 
>     def get_sync_gateway_document_count(self, db):
>         docs = self.admin.get_all_docs(db)
> ```

Could this be removed?  Are the old tests even running in an automated way?

---

*[keywords/TKClient.py, line 63 \[r2\]](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/441#-KHMGT2RPTwK7uhIqVY8:-KHMGT2RPTwK7uhIqVY9:1426803477) ([raw file](https://github.com/couchbaselabs/mobile-testkit/blob/ec05e83da3e918fb916b9b1279ea99680e558c39/keywords/TKClient.py#L63)):*
> ```Python
>     return {"rows": rows}
> 
> class TKClient:
> ```

MobileRestClient

In comments, mention that this is useful against:

* Sync Gateway
* Liteserve on client platforms 

---

*[keywords/TKClient.py, line 174 \[r2\]](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/441#-KHMH1Oz5_Bb147t26gd:-KHMH1Oz5_Bb147t26ge:-510090734) ([raw file](https://github.com/couchbaselabs/mobile-testkit/blob/ec05e83da3e918fb916b9b1279ea99680e558c39/keywords/TKClient.py#L174)):*
> ```Python
>     def verify_docs_present(self, url, db, expected_docs):
>         """
>         Verifies that the docs passed in the function exist in the database
> ```

Can you specify what's allowable for expected_docs?  Map?  List?  

---

*[keywords/TKClient.py, line 242 \[r2\]](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/441#-KHMHY-A2z8g2pJrQKeW:-KHMHY-A2z8g2pJrQKeX:717832756) ([raw file](https://github.com/couchbaselabs/mobile-testkit/blob/ec05e83da3e918fb916b9b1279ea99680e558c39/keywords/TKClient.py#L242)):*
> ```Python
>             break
> 
>     def verify_docs_in_changes(self, url, db, expected_docs):
> ```

Not for this PR, but could be cleaner to take retry logic out of this and move to a shared decorator wrapper function

---

*[libraries/data/generators.py, line 7 \[r2\]](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/441#-KHMIADxIVdu3nhI07xN:-KHMIADxIVdu3nhI07xO:316486413) ([raw file](https://github.com/couchbaselabs/mobile-testkit/blob/ec05e83da3e918fb916b9b1279ea99680e558c39/libraries/data/generators.py#L7)):*
> ```Python
> import json
> import datetime
> ```

Could this be renamed to doc_generators?

Also add a brief explanation to the top of the file .. although might be obvious from name.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/441)*

**Comment by sethrosetter** [comment]
Review status: 15 of 26 files reviewed at latest revision, 11 unresolved discussions.

---

*[setup.sh, line 1 \[r2\]](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/441#-KHMBeKnKP1Bsiu2muXx:-KHMsnnCt3mWC0XHPe7N:-499146009) ([raw file](https://github.com/couchbaselabs/mobile-testkit/blob/ec05e83da3e918fb916b9b1279ea99680e558c39/setup.sh#L1)):*
<details><summary><i>Previously, tleyden (Traun Leyden) wrote…</i></summary>
> The top of this file should have a description of what this is doing at a high level</details>
Done.

---

*[setup.sh, line 15 \[r2\]](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/441#-KHMByjnECwOWc6L_FhV:-KHMsn-mTMN91X-ui7v4:-499146009) ([raw file](https://github.com/couchbaselabs/mobile-testkit/blob/ec05e83da3e918fb916b9b1279ea99680e558c39/setup.sh#L15)):*
<details><summary><i>Previously, tleyden (Traun Leyden) wrote…</i></summary>
> Move this to beginning of script so it's in a weird state</details>
Done.

---

*[keywords/Async.py, line 5 \[r2\]](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/441#-KHMCvGXsfB9pjK2zNLf:-KHMsm-GrC0cvDTPJK_4:-499146009) ([raw file](https://github.com/couchbaselabs/mobile-testkit/blob/ec05e83da3e918fb916b9b1279ea99680e558c39/keywords/Async.py#L5)):*
<details><summary><i>Previously, tleyden (Traun Leyden) wrote…</i></summary>
> Add something to the top of the file that says:
> 
> * What this does (high level overview)
> * That it's experimental and not being used yet</details>
Done.

---

*[keywords/MobileRestClient.py, line 63 \[r2\]](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/441#-KHMGT2RPTwK7uhIqVY8:-KHMscp7Y17J8PBfnZo8:-499146009) ([raw file](https://github.com/couchbaselabs/mobile-testkit/blob/ec05e83da3e918fb916b9b1279ea99680e558c39/keywords/MobileRestClient.py#L63)):*
<details><summary><i>Previously, tleyden (Traun Leyden) wrote…</i></summary>
> MobileRestClient
> 
> In comments, mention that this is useful against:
> 
> * Sync Gateway
> * Liteserve on client platforms </details>
Done.

---

*[keywords/MobileRestClient.py, line 174 \[r2\]](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/441#-KHMH1Oz5_Bb147t26gd:-KHMsdHCpbrm_CsiexyS:-499146009) ([raw file](https://github.com/couchbaselabs/mobile-testkit/blob/ec05e83da3e918fb916b9b1279ea99680e558c39/keywords/MobileRestClient.py#L174)):*
<details><summary><i>Previously, tleyden (Traun Leyden) wrote…</i></summary>
> Can you specify what's allowable for expected_docs?  Map?  List?  </details>
Done.

---

*[keywords/MobileRestClient.py, line 242 \[r2\]](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/441#-KHMHY-A2z8g2pJrQKeW:-KHMsdoCn8ZBu0XiderY:-1694434062) ([raw file](https://github.com/couchbaselabs/mobile-testkit/blob/ec05e83da3e918fb916b9b1279ea99680e558c39/keywords/MobileRestClient.py#L242)):*
<details><summary><i>Previously, tleyden (Traun Leyden) wrote…</i></summary>
> Not for this PR, but could be cleaner to take retry logic out of this and move to a shared decorator wrapper function</details>
I will look into it.

---

*[keywords/SyncGateway.py, line 112 \[r2\]](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/441#-KHMF5YSibDGeKhYq7O8:-KHMs_RmSuZHYoLrc4jY:-499146009) ([raw file](https://github.com/couchbaselabs/mobile-testkit/blob/ec05e83da3e918fb916b9b1279ea99680e558c39/keywords/SyncGateway.py#L112)):*
<details><summary><i>Previously, tleyden (Traun Leyden) wrote…</i></summary>
> Could this be removed?  Are the old tests even running in an automated way?</details>
Done.

---

*[libraries/data/doc_generators.py, line 7 \[r2\]](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/441#-KHMIADxIVdu3nhI07xN:-KHMsem-NWwMpzUQvkbB:-499146009) ([raw file](https://github.com/couchbaselabs/mobile-testkit/blob/ec05e83da3e918fb916b9b1279ea99680e558c39/libraries/data/doc_generators.py#L7)):*
<details><summary><i>Previously, tleyden (Traun Leyden) wrote…</i></summary>
> Could this be renamed to doc_generators?
> 
> Also add a brief explanation to the top of the file .. although might be obvious from name.</details>
Done.

---

*[scripts/run_listener_tests_android.sh, line 2 \[r2\]](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/441#-KHMAWbkpv6MMH_Z4Mj7:-KHMsfG3KgfJJV4VokF8:-499146009) ([raw file](https://github.com/couchbaselabs/mobile-testkit/blob/ec05e83da3e918fb916b9b1279ea99680e558c39/scripts/run_listener_tests_android.sh#L2)):*
<details><summary><i>Previously, tleyden (Traun Leyden) wrote…</i></summary>
> Take this out of the repo, and add to the README.  (for your local system, you can have a hidden directory)
> 
> In readme, add some explanation how users can figure out what values to use for these variables.
> </details>
Done.

---

*[scripts/run_listener_tests_macosx.sh, line 2 \[r2\]](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/441#-KHMBMDXyXHynZwV0so0:-KHMsfZTlxqNa6ZiOV8v:-499146009) ([raw file](https://github.com/couchbaselabs/mobile-testkit/blob/ec05e83da3e918fb916b9b1279ea99680e558c39/scripts/run_listener_tests_macosx.sh#L2)):*
<details><summary><i>Previously, tleyden (Traun Leyden) wrote…</i></summary>
> Ditto on other .sh file</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/441)*

**Comment by tleyden** [comment]
Reviewed 15 of 21 files at r3, 4 of 5 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/441)*

**Comment by sethrosetter** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[setup.sh, line 12 \[r2\]](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/441#-KHMCAaRau_KrT5bQH3o:-KHMxnKHl0r_Ue4ZXAus:5174689) ([raw file](https://github.com/couchbaselabs/mobile-testkit/blob/ec05e83da3e918fb916b9b1279ea99680e558c39/setup.sh#L12)):*
<details><summary><i>Previously, tleyden (Traun Leyden) wrote…</i></summary>
> Just sent this to you proactively</details>
ok

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/441)*

**Pull request merged**
