### PR TITLE
Feature/direct ansible

### PR DESCRIPTION
**Pull request by tleyden**
This change is [Reviewable](https://reviewable.io/reviews/couchbaselabs/mobile-testkit/490)

### CODE REVIEW

**Comment by sethrosetter** [comment]
Reviewed 13 of 17 files at r1.
Review status: 13 of 17 files reviewed at latest revision, 4 unresolved discussions.

---

*[libraries/provision/ansible_python_runner.py, line 142 \[r1\]](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/490#-KJ7QrbVZ0c6XEf6Wfsa:-KJ7QrbWy3MDhY-81xqy:-1543709504) ([raw file](https://github.com/couchbaselabs/mobile-testkit/blob/a74caaaf648d057b94da5d388daf4337151813e8/libraries/provision/ansible_python_runner.py#L142)):*
> ```Python
>         stats = self.pbex._tqm._stats
> 
>         # Test if success for record_logs
> ```

Can this code be removed? It looks like it is a callback for something we are not using?

---

*[libraries/provision/ansible_runner.py, line 24 \[r1\]](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/490#-KJ7R2O7i48iATWbtkwC:-KJ7R2O7i48iATWbtkwD:203628079) ([raw file](https://github.com/couchbaselabs/mobile-testkit/blob/a74caaaf648d057b94da5d388daf4337151813e8/libraries/provision/ansible_runner.py#L24)):*
> ```Python
>         )
> 
>         stats = runner.run()
> ```

Can you add logging.info(stats) here?

---

*[libraries/provision/provision_cluster.py, line 17 \[r1\]](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/490#-KJ7RPP70whHrfOmgyjR:-KJ7RPP70whHrfOmgyjS:1986597621) ([raw file](https://github.com/couchbaselabs/mobile-testkit/blob/a74caaaf648d057b94da5d388daf4337151813e8/libraries/provision/provision_cluster.py#L17)):*
> ```Python
> def provision_cluster(couchbase_server_config, sync_gateway_config, install_deps):
> 
>     test_output("\n>>> Host info:\n")
> ```

Maybe we need a different name here?

---

*[libraries/provision/ansible/callbacks/robot_tee.py, line 18 \[r1\]](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/490#-KJ7S4hlGcyCgAnGKwIM:-KJ7S4hlGcyCgAnGKwIN:-1370029785) ([raw file](https://github.com/couchbaselabs/mobile-testkit/blob/a74caaaf648d057b94da5d388daf4337151813e8/libraries/provision/ansible/callbacks/robot_tee.py#L18)):*
> ```Python
>     def v2_playbook_on_task_start(self, task, is_conditional):
>         if len(task.name) > 0:
>             console("TASK [{}] ---------------------------------------------- ".format(task.name))
> ```

I think we should use `from robot.api.logger import info` (https://github.com/robotframework/robotframework/blob/master/src/robot/api/logger.py#L109-L117) and user info(blah, also_console=True). This way, all the provisioning output will be added to the html results as well

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/490)*

**Comment by sethrosetter** [comment]
Reviewed 4 of 17 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/490)*

**Comment by tleyden** [comment]
*[a discussion](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/490#-KJ88eyj39H2XQbUwWa1:-KJ88eyj39H2XQbUwWa2:1559391421) (no related file):*
Passing build:

http://uberjenkins.sc.couchbase.com:8080/view/QE%20Dev/job/syncgateway-functional-tests-dev/113/console

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/490)*

**Comment by tleyden** [comment]
*[a discussion](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/490#-KJ88eyj39H2XQbUwWa1:-KJ895oWLdFk6owCcTBQ:-703438123) (no related file):*
<details><summary><i>Previously, tleyden (Traun Leyden) wrote…</i></summary>
> Passing build:
> 
> http://uberjenkins.sc.couchbase.com:8080/view/QE%20Dev/job/syncgateway-functional-tests-dev/113/console
> 
> 
</details>
Build in progress:

http://uberjenkins.sc.couchbase.com:8080/view/QE%20Dev/job/syncgateway-functional-tests-dev/114/console

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/490)*

**Comment by sethrosetter** [comment]
Reviewed 3 of 4 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/couchbaselabs/mobile-testkit/490)*

**Pull request merged**
