### PR TITLE
Add usernames to all SG configs

### PR DESCRIPTION
**Pull request by raghusarangapani**
#### Fixes #.

- [x] Ran `flake8`
- [x] Ran `run_repo_tests.sh`

#### Changes proposed in this pull request:
- Add usernames to buckets for all SG configs

### CODE REVIEW

**Comment by sethrosetter** [comment]
Can you kick off the 4 sync gateway tests?

**Comment by raghusarangapani** [comment]
Kicked off these runs, will update once done.

SG 1.4.1-3:
http://uberjenkins.sc.couchbase.com/job/cen7-sync-gateway-functional-tests-base-cc/515/

SG 1.3.1-16:
http://uberjenkins.sc.couchbase.com/job/cen7-sync-gateway-functional-tests-base-di/462/
http://uberjenkins.sc.couchbase.com/job/cen7-sync-gateway-functional-tests-topology-specific-di/373/

SG 1.2.1-4:
http://uberjenkins.sc.couchbase.com/job/cen7-sync-gateway-functional-tests-topology-specific-cc/392/

**Comment by tleyden** [comment]
Which issue/error does this fix?  I might be seeing this locally on distributed index tests.

Here are my logs:

https://gist.github.com/tleyden/1aff26c48024f57b6bbfba3b1638623c

**Comment by tleyden** [comment]
That error was against couchbase server 4.6.1, but I'm on a different branch than master and so it might be specific to my branch.

**Pull request merged**
