### PR TITLE
Remove feed_type from di configs

### LINKED ISSUE #1040: Audit FeedType in config
We should remove FeedType so that sg uses default to prep for DCP by default change

### PR DESCRIPTION
**Pull request by raghusarangapani**
#### Fixes #1040.

- [x] Ran `flake8`
- [x] Ran `run_repo_tests.sh`

#### Changes proposed in this pull request:
- Remove feed_type from di configs

### CODE REVIEW

**Comment by sethrosetter** [comment]
@adamcfraser Just to double check, `feed_type` is not required in the config for 1.4.0+, right? Just making sure for version interop testing.

**Comment by adamcfraser** [comment]
PR looks good to me.  

@sethrosetter I don't recall exactly when feed_type was made a non-required parameter.

**Comment by sethrosetter** [comment]
@adamcfraser is that pretty easy to look up? If it is pre 1.4 GA, I am fine merging this since we only run DI tests on 1.4+, however I would like to avoid the case where our 1.4 tests start to fail because of this.

**Comment by sethrosetter** [comment]
@raghusarangapani Can you kick off a base_di run with `1.4.1-3` and this branch to see if it works?

**Comment by raghusarangapani** [comment]
Kicked off http://uberjenkins.sc.couchbase.com/job/cen7-sync-gateway-functional-tests-base-di/618

**Pull request merged**
